"""Repository inventory, classification, coverage tables, and shard planning."""

import math
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

from .common import (
    BOUNDARY_CLASSES,
    CLASS_ORDER,
    INITIAL_STATUS,
    MAX_SHARD_FILES,
    READ_CLASSES,
    bar,
    default_rubric,
    dump,
    fmt,
    git,
    plural,
    rubric_headings,
)

VENDOR_SEGMENTS = {"vendor", "vendored", "third_party", "third-party", "node_modules", "extern", "external"}
GENERATED_SEGMENTS = {"generated", "__generated__", "gen", "dist", "build"}
GENERATED_NAME = re.compile(r"(\.pb\.|_pb2(_grpc)?\.py$|\.min\.(js|css)$|\.generated\.|\.g\.dart$)")
GENERATED_MARKER = re.compile(r"(@generated|do not edit|auto-?generated|generated by)", re.IGNORECASE)
DATA_SEGMENTS = {"fixtures", "fixture", "__fixtures__", "testdata", "snapshots", "__snapshots__"}
DATA_NAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock", "gemfile.lock",
    "composer.lock", "go.sum", "uv.lock", "pipfile.lock", "bun.lockb",
}
DATA_PREFIXES = ("license", "notice", "copying")
DATA_EXT = {".csv", ".tsv", ".parquet", ".jsonl", ".ndjson", ".svg", ".snap", ".lock", ".pdf"}
TEST_SEGMENTS = {"test", "tests", "spec", "specs", "__tests__", "e2e"}
TEST_NAME = re.compile(r"(^test_.*\.py$|_test\.[^.]+$|\.test\.[^.]+$|\.spec\.[^.]+$|^conftest\.py$)")
SCHEMA_SEGMENTS = {"migrations", "migration", "schema", "schemas"}
SCHEMA_EXT = {".sql", ".prisma", ".graphql", ".gql", ".proto", ".avsc", ".thrift", ".xsd"}
CONFIG_NAMES = {
    "dockerfile", "procfile", "codeowners", ".env.example", ".editorconfig", ".gitattributes",
    ".gitignore", ".npmrc", ".nvmrc",
}
CONFIG_EXT = {".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".properties", ".tf", ".hcl"}
SCRIPT_NAMES = {"makefile", "justfile", "rakefile"}
SCRIPT_SEGMENTS = {"scripts", "script", "bin", "tools"}
SCRIPT_EXT = {".sh", ".bash", ".zsh", ".fish", ".ps1", ".bat", ".cmd"}
DOC_EXT = {".md", ".mdx", ".rst", ".txt", ".adoc", ".asciidoc"}


def classify(rel, repo, attrs, overrides):
    """Classify one inventoried path and record the rule that excluded it from full reading."""
    path = Path(rel)
    name = path.name.lower()
    segments = {segment.lower() for segment in path.parts[:-1]}
    ext = path.suffix.lower()
    full = repo / rel
    try:
        head = full.open("rb").read(8192)
    except OSError as error:
        return "binary", f"unreadable: {error.strerror}", 0
    if b"\0" in head:
        return "binary", "binary content", 0
    lines = full.read_bytes().count(b"\n")
    first = head.decode("utf-8", "replace").splitlines()[:8]
    for prefix, cls in overrides:
        if rel == prefix or rel.startswith(prefix.rstrip("/") + "/"):
            return cls, f"--override {prefix}={cls}", lines
    attr = attrs.get(rel, {})
    if attr.get("linguist-vendored") == "true" or segments & VENDOR_SEGMENTS:
        return "vendored", "vendored directory or linguist-vendored", lines
    if attr.get("linguist-generated") == "true":
        return "generated", "linguist-generated attribute", lines
    if segments & GENERATED_SEGMENTS or GENERATED_NAME.search(name):
        return "generated", "generated path or name pattern", lines
    if any(GENERATED_MARKER.search(line) for line in first):
        return "generated", "generated marker in header", lines
    if name in DATA_NAMES or name.startswith(DATA_PREFIXES) or ext in DATA_EXT:
        return "data", "lockfile, license, notice, or data format", lines
    if segments & DATA_SEGMENTS:
        return "data", "fixture or snapshot: name assessed, content not read", lines
    if segments & TEST_SEGMENTS or TEST_NAME.search(name):
        return "test", "", lines
    if segments & SCHEMA_SEGMENTS or ext in SCHEMA_EXT or name.startswith("schema."):
        return "schema", "", lines
    if name in CONFIG_NAMES or name.startswith("dockerfile") or name.startswith("requirements") and ext == ".txt":
        return "config", "", lines
    if ext in CONFIG_EXT or (len(path.parts) == 1 and name.startswith(".")):
        return "config", "", lines
    if name in SCRIPT_NAMES or ext in SCRIPT_EXT or segments & SCRIPT_SEGMENTS:
        return "script", "", lines
    if ext in DOC_EXT or name.startswith("changelog"):
        return "docs", "", lines
    return "source", "", lines


def read_attrs(repo, paths):
    """Read GitHub Linguist classification attributes for every inventory candidate."""
    out = subprocess.run(
        ["git", "-C", str(repo), "check-attr", "linguist-generated", "linguist-vendored", "--stdin"],
        input="\n".join(paths), capture_output=True, text=True, check=False,
    ).stdout
    attrs = defaultdict(dict)
    for line in out.splitlines():
        parts = line.rsplit(": ", 2)
        if len(parts) == 3:
            attrs[parts[0]][parts[1]] = parts[2]
    return attrs


def plan_shards(files, shard_lines):
    """Balance total reading load; keep path order inside each deterministic shard."""
    if not files:
        return []
    count = max(
        1,
        math.ceil(sum(file["lines"] for file in files) / shard_lines),
        math.ceil(len(files) / MAX_SHARD_FILES),
    )
    groups = [{"paths": [], "lines": 0} for _ in range(count)]
    for file in sorted(files, key=lambda value: (-value["lines"], value["path"])):
        available = [group for group in groups if len(group["paths"]) < MAX_SHARD_FILES]
        group = min(available, key=lambda value: (value["lines"], len(value["paths"]), value["paths"]))
        group["paths"].append(file["path"])
        group["lines"] += file["lines"]
    groups = sorted((sorted(group["paths"]) for group in groups if group["paths"]), key=lambda paths: paths[0])
    by_path = {file["path"]: file["lines"] for file in files}
    return [
        {
            "id": f"S-{index:02d}", "files": paths, "lines": sum(by_path[path] for path in paths),
            "status": "pending", "parent": None,
        }
        for index, paths in enumerate(groups, 1)
    ]


def parse_name_status(raw):
    """Turn `git diff -z --name-status` output into change records that keep a rename's old path."""
    tokens = raw.split("\0")
    changed, index = [], 0
    while index < len(tokens) and tokens[index]:
        status = tokens[index][0]
        if status in "RC":
            changed.append({"path": tokens[index + 2], "status": status, "old_path": tokens[index + 1]})
            index += 3
        else:
            changed.append({"path": tokens[index + 1], "status": status})
            index += 2
    return changed


def resolve_range(repo, base_input):
    """Pin the audited delta to merge-base(BASE, HEAD)..HEAD, the three-dot range a pull request shows."""
    head = git(repo, "rev-parse", "HEAD").strip()
    base = git(repo, "rev-parse", "--verify", "--quiet", f"{base_input}^{{commit}}").strip()
    if not base:
        sys.exit(f"--base {base_input} does not resolve to a commit")
    merge_base = git(repo, "merge-base", base, head).strip()
    if not merge_base:
        sys.exit(f"--base {base_input} ({base[:12]}) has no merge base with HEAD ({head[:12]})")
    dirty = [line for line in git(repo, "status", "--porcelain").splitlines() if not line.startswith("??")]
    if dirty:
        sys.exit(
            f"working tree differs from HEAD ({head[:12]}) in {plural(len(dirty), 'tracked entry')}; "
            "evidence must agree with HEAD, so commit or discard them first"
        )
    # -C alone only pairs a copy with a source touched in the same range; unchanged sources need the harder search.
    changed = parse_name_status(
        git(repo, "diff", "-z", "--name-status", "-M", "-C", "--find-copies-harder", merge_base, head)
    )
    if not changed:
        sys.exit(f"empty range: {merge_base[:12]}..{head[:12]} changes no files")
    # Every surviving changed path must be inventoried as itself: a gitlink cannot be read, and a symlink would
    # be read as its target, possibly outside the repository, so stop instead of omitting or substituting it.
    unsupported = [
        change["path"] for change in changed
        if change["status"] != "D" and ((repo / change["path"]).is_symlink() or not (repo / change["path"]).is_file())
    ]
    if unsupported:
        sys.exit(
            f"changed paths in {merge_base[:12]}..{head[:12]} are not regular files "
            f"(submodule, symlink, or special entry): {', '.join(unsupported)}"
        )
    return {"base_input": base_input, "base": base, "merge_base": merge_base, "head": head, "changed": changed}


def range_table(inventory):
    """Render the exact audited delta: every SHA, every change kind, and the searched context count."""
    audited = inventory["range"]
    files = inventory["files"]
    kinds = Counter(change["status"] for change in audited["changed"])
    labels = {"A": "added", "M": "modified", "R": "renamed", "C": "copied", "D": "deleted", "T": "type-changed"}
    context = [file for file in files if file["treatment"] == "context"]
    out = [
        f"RANGE  merge-base {audited['merge_base'][:12]}..HEAD {audited['head'][:12]}",
        f"  base       {audited['base_input']} = {audited['base']}",
        f"  merge-base {audited['merge_base']}",
        f"  head       {audited['head']}",
        "  changed    " + ", ".join(f"{labels.get(status, status)} {count}" for status, count in sorted(kinds.items())),
    ]
    for change in audited["changed"]:
        if change.get("old_path"):
            out.append(f"  {labels[change['status']]:10} {change['old_path']} -> {change['path']}")
    for change in audited["changed"]:
        if change["status"] == "D":
            out.append(f"  deleted    {change['path']}")
    out.append(
        f"  context    {plural(len(context), 'unchanged file')}, {fmt(sum(file['lines'] for file in context))} lines: "
        "searched for reach and blast radius, never read or scored"
    )
    return "\n".join(out)


def coverage_table(inventory, ledger):
    """Render the authoritative coverage counts and treatment legend."""
    files = [file for file in (ledger["files"] if ledger else inventory["files"]) if file["treatment"] != "context"]
    total_lines = sum(file["lines"] for file in files)
    unit = max(1, total_lines // 38) if total_lines else 1
    out = [f"COVERAGE                                              scale: one # = {fmt(unit)} lines"]
    out.append(f"  {'class':10} {'files':>6} {'lines':>9}  {'':38}  {'read':>5} {'bndry':>5} {'list':>5} {'uncov':>5} {'pend':>5}")
    for cls in CLASS_ORDER:
        group = [file for file in files if file["class"] == cls]
        if not group:
            continue
        lines = sum(file["lines"] for file in group)
        status = Counter(file.get("status", INITIAL_STATUS[file["treatment"]]) for file in group)
        mark = bar(lines, unit, 38) if cls in READ_CLASSES else "." * len(bar(lines, unit, 38))
        out.append(
            f"  {cls:10} {len(group):6d} {fmt(lines):>9}  {mark:38}  {status['read-in-full']:5d} "
            f"{status['boundary-only']:5d} {status['listed']:5d} {status['uncovered']:5d} {status['pending']:5d}"
        )
    out.append(f"  {'total':10} {len(files):6d} {fmt(total_lines):>9}")
    out.append("  bars: '#' classes are read in full, '.' classes are boundary-checked or listed only")
    if inventory.get("range"):
        context = [file for file in (ledger["files"] if ledger else inventory["files"]) if file["treatment"] == "context"]
        out.append(
            f"  counts cover changed files only; {plural(len(context), 'unchanged context file')} "
            "searched, never read or scored"
        )
    return "\n".join(out)


def exclusion_table(files):
    """Render every non-read class with its classification reason and directories."""
    out = ["EXCLUSIONS  (not read in full; every count is from the inventory)"]
    groups = defaultdict(list)
    for file in files:
        if file["treatment"] not in ("read", "context"):
            groups[(file["class"], file["reason"])].append(file)
    if not groups:
        out.append("  none")
    for (cls, reason), group in sorted(groups.items()):
        dirs = Counter(str(Path(file["path"]).parent) for file in group)
        top = ", ".join(f"{directory}/ ({count})" for directory, count in dirs.most_common(3))
        out.append(f"  {cls:10} {len(group):5d} files  {fmt(sum(file['lines'] for file in group)):>9} lines  {reason}")
        out.append(f"  {'':10} {'':5}        {'':9}        in {top}")
    return "\n".join(out)


def cmd_inventory(args):
    """Build immutable repository facts and a balanced shard plan."""
    repo = Path(git(args.repo, "rev-parse", "--show-toplevel").strip() or sys.exit("not a git repository"))
    work = Path(args.work)
    if work.resolve().is_relative_to(repo.resolve()):
        sys.exit("work directory must live outside the audited repository")
    # A change-range audit claims the whole delta; a scoped subset would silently omit changed paths.
    if args.base and args.scope:
        sys.exit("--base audits every path in merge-base(BASE, HEAD)..HEAD and cannot be combined with --scope")
    work.mkdir(parents=True, exist_ok=True)
    audited = resolve_range(repo, args.base) if args.base else None
    tracked = git(repo, "ls-files", "-z").split("\0")
    # A change-range audit is a claim about HEAD, so untracked files stay out of its searchable context.
    untracked = [] if audited else git(repo, "ls-files", "-z", "--others", "--exclude-standard").split("\0")
    paths = sorted({path for path in tracked + untracked if path})
    scope = [value.strip("/") for value in args.scope]
    if scope:
        paths = [path for path in paths if any(path == value or path.startswith(value + "/") for value in scope)]
    attrs = read_attrs(repo, paths)
    if args.shard_lines <= 0:
        sys.exit("--shard-lines must be positive")
    overrides = []
    for item in args.override:
        prefix, _, cls = item.partition("=")
        prefix = prefix.strip("/")
        if not prefix:
            sys.exit("--override needs a non-empty repository-relative prefix")
        if cls not in CLASS_ORDER:
            sys.exit(f"--override class must be one of {', '.join(CLASS_ORDER)}")
        overrides.append((prefix, cls))
    for prefix, _ in overrides:
        if not any(path == prefix or path.startswith(prefix + "/") for path in paths):
            print(f"warning: --override prefix matches no inventory path: {prefix}", file=sys.stderr)
    changed_by_path = {change["path"]: change for change in audited["changed"]} if audited else None
    files = []
    for rel in paths:
        if not (repo / rel).is_file():
            continue
        cls, reason, lines = classify(rel, repo, attrs, overrides)
        treatment = "read" if cls in READ_CLASSES else "boundary" if cls in BOUNDARY_CLASSES else "listed"
        file = {"path": rel, "class": cls, "treatment": treatment, "lines": lines, "reason": reason}
        if changed_by_path is not None:
            change = changed_by_path.get(rel)
            if change is None:
                file["treatment"] = "context"
            else:
                file["change"] = change["status"]
                if change.get("old_path"):
                    file["old_path"] = change["old_path"]
        files.append(file)
    rubric = Path(args.rubric) if args.rubric else default_rubric()
    inventory = {
        "repo": str(repo),
        "origin": git(repo, "remote", "get-url", "origin", check=False).strip(),
        "head": git(repo, "rev-parse", "HEAD").strip(),
        "branch": git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip(),
        "dirty": git(repo, "status", "--porcelain").splitlines(),
        "scope": scope,
        "range": audited,
        "rubric": str(rubric),
        "properties": rubric_headings(rubric),
        "shard_lines": args.shard_lines,
        "files": files,
    }
    dump(work / "inventory.json", inventory)
    shards = plan_shards([file for file in files if file["treatment"] == "read"], args.shard_lines)
    dump(work / "shards.json", {"shards": shards})
    (work / "shards").mkdir(exist_ok=True)
    if audited:
        print(f"{range_table(inventory)}\n")
    print(coverage_table(inventory, None))
    print(f"\n{exclusion_table(files)}\n")
    print(f"SHARD PLAN  {plural(len(shards), 'shard')}, target {fmt(args.shard_lines)} lines, max {MAX_SHARD_FILES} files")
    for shard in shards:
        first, last = shard["files"][0], shard["files"][-1]
        print(f"  {shard['id']}  {len(shard['files']):4d} files  {fmt(shard['lines']):>8} lines  {first} .. {last}")
    print(f"\nproperties: {len(inventory['properties'])} from {rubric}")
    counted = [file for file in files if file["treatment"] != "context"]
    classes = Counter(file["class"] for file in counted)
    class_text = " · ".join(f"{cls} {classes[cls]}" for cls in CLASS_ORDER if classes[cls])
    noun = "changed file" if audited else "file"
    context_text = f"; {plural(len(files) - len(counted), 'context file')} searched" if audited else ""
    print(
        f"inventory: {plural(len(counted), noun)}, {fmt(sum(file['lines'] for file in counted))} lines; "
        f"{class_text}; {plural(len(shards), 'shard')}{context_text}"
    )
