#!/usr/bin/env python3
"""Inventory, verify, and render an evidence-backed test audit."""

import argparse
import hashlib
import json
import math
import re
import subprocess
from collections import Counter
from pathlib import Path

READ_CLASSES = ("source", "test", "config", "script", "schema", "docs")
BOUNDARY_CLASSES = ("generated", "vendored")
LISTED_CLASSES = ("data", "binary")
CLASS_ORDER = READ_CLASSES + BOUNDARY_CLASSES + LISTED_CLASSES
TEST_SEGMENTS = {"test", "tests", "spec", "specs", "__tests__", "e2e"}
VENDOR_SEGMENTS = {
    "vendor",
    "vendored",
    "third_party",
    "third-party",
    "node_modules",
    "external",
}
GENERATED_SEGMENTS = {"generated", "__generated__", "dist", "build"}
DATA_SEGMENTS = {
    "fixtures",
    "fixture",
    "__fixtures__",
    "testdata",
    "snapshots",
    "__snapshots__",
}
TEST_NAME = re.compile(
    r"(^test_.*\.py$|_test\.[^.]+$|\.test\.[^.]+$|\.spec\.[^.]+$|^conftest\.py$)"
)
GENERATED_NAME = re.compile(
    r"(\.pb\.|_pb2(_grpc)?\.py$|\.min\.(js|css)$|\.generated\.|\.g\.dart$)"
)
GENERATED_MARKER = re.compile(
    r"(@generated|do not edit|auto-?generated|generated by)", re.IGNORECASE
)
SCHEMA_EXT = {
    ".sql",
    ".prisma",
    ".graphql",
    ".gql",
    ".proto",
    ".avsc",
    ".thrift",
    ".xsd",
}
CONFIG_EXT = {
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".properties",
    ".tf",
    ".hcl",
}
SCRIPT_EXT = {".sh", ".bash", ".zsh", ".fish", ".ps1", ".bat", ".cmd"}
DOC_EXT = {".md", ".mdx", ".rst", ".txt", ".adoc", ".asciidoc"}
DATA_NAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "cargo.lock",
    "go.sum",
    "uv.lock",
}
TEST_RISK = {"high", "medium", "low", "none"}
TEST_VERDICTS = {"keep", "delete", "consolidate", "rewrite"}
IMPACTS = {"high", "medium", "low"}
COVERAGE = {"covered", "partial", "missing", "manual", "not-warranted"}
FINDING_KINDS = {"gap", "bloat", "false-confidence"}
SEVERITIES = {"HIGH", "MED", "LOW"}
IMPACT_WEIGHT = {"high": 4, "medium": 2, "low": 1}
COVERAGE_CREDIT = {"covered": 1.0, "partial": 0.5, "missing": 0.0}
SIGNAL_CREDIT = {"keep": 1.0, "consolidate": 0.5, "rewrite": 0.5, "delete": 0.0}


def fail(message):
    raise SystemExit(message)


def git(repo, *args):
    result = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True, check=False
    )
    if result.returncode not in (0, 1):
        fail(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def load(path):
    path = Path(path)
    if not path.exists():
        fail(f"missing {path}")
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as error:
        fail(f"invalid JSON in {path} at line {error.lineno}, column {error.colno}")


def dump(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def line_count(path):
    data = path.read_bytes()
    return len(data.splitlines())


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def repository_paths(repo, scopes):
    paths = sorted(
        set(
            filter(
                None,
                (
                    git(repo, "ls-files", "-z")
                    + git(repo, "ls-files", "-z", "--others", "--exclude-standard")
                ).split("\0"),
            )
        )
    )
    if scopes:
        paths = [
            path
            for path in paths
            if any(path == scope or path.startswith(scope + "/") for scope in scopes)
        ]
    return paths


def classify(rel, repo, overrides):
    path = Path(rel)
    name = path.name.lower()
    segments = {part.lower() for part in path.parts[:-1]}
    ext = path.suffix.lower()
    full = repo / rel
    if full.is_symlink():
        return "binary", "symlink target not read", 0
    if not full.is_file():
        return "binary", "missing or special Git entry", 0
    try:
        head = full.open("rb").read(8192)
    except OSError as error:
        return "binary", f"unreadable: {error.strerror}", 0
    lines = line_count(full)
    if b"\0" in head:
        return "binary", "binary content", lines
    for prefix, cls in overrides:
        if rel == prefix or rel.startswith(prefix.rstrip("/") + "/"):
            return cls, f"--override {prefix}={cls}", lines
    first = head.decode("utf-8", "replace").splitlines()[:8]
    if segments & VENDOR_SEGMENTS:
        return "vendored", "vendored directory", lines
    if segments & GENERATED_SEGMENTS or GENERATED_NAME.search(name):
        return "generated", "generated path or name", lines
    if any(GENERATED_MARKER.search(line) for line in first):
        return "generated", "generated marker", lines
    if name in DATA_NAMES:
        return "data", "lockfile", lines
    if segments & (TEST_SEGMENTS | DATA_SEGMENTS) or TEST_NAME.search(name):
        return "test", "", lines
    if ext in {".csv", ".tsv", ".parquet", ".jsonl", ".snap", ".lock", ".pdf"}:
        return "data", "data format", lines
    if ext in SCHEMA_EXT or segments & {"schema", "schemas", "migration", "migrations"}:
        return "schema", "", lines
    if ext in CONFIG_EXT or name.startswith("."):
        return "config", "", lines
    if (
        ext in SCRIPT_EXT
        or segments & {"scripts", "script", "bin", "tools"}
        or name in {"makefile", "justfile"}
    ):
        return "script", "", lines
    if ext in DOC_EXT or name.startswith(("readme", "changelog", "license")):
        return "docs", "", lines
    return "source", "", lines


def rubric_properties(path):
    properties = [
        line[4:].strip()
        for line in Path(path).read_text().splitlines()
        if line.startswith("### ")
    ]
    if not properties:
        fail(f"no rubric properties found in {path}")
    return properties


def plan_shards(files, target_lines):
    if not files:
        return []
    count = max(
        1,
        math.ceil(sum(item["lines"] for item in files) / target_lines),
        math.ceil(len(files) / 200),
    )
    groups = [{"files": [], "lines": 0} for _ in range(count)]
    for item in sorted(files, key=lambda value: (-value["lines"], value["path"])):
        group = min(groups, key=lambda value: (value["lines"], len(value["files"])))
        group["files"].append(item["path"])
        group["lines"] += item["lines"]
    groups.sort(key=lambda value: min(value["files"]))
    return [
        {
            "id": f"S-{index:02d}",
            "files": sorted(group["files"]),
            "lines": group["lines"],
        }
        for index, group in enumerate(groups, 1)
    ]


def command_inventory(args):
    repo = Path(
        git(args.repo, "rev-parse", "--show-toplevel").strip()
        or fail("not a Git repository")
    ).resolve()
    work = Path(args.work).resolve()
    if work == repo or repo in work.parents:
        fail("work directory must be outside the audited repository")
    if args.shard_lines <= 0:
        fail("--shard-lines must be positive")
    overrides = []
    for raw in args.override:
        prefix, separator, cls = raw.partition("=")
        prefix = prefix.strip("/")
        if not separator or not prefix or cls not in CLASS_ORDER:
            fail(
                f"--override must be PREFIX=CLASS where CLASS is one of {', '.join(CLASS_ORDER)}"
            )
        overrides.append((prefix, cls))
    scopes = [scope.strip("/") for scope in args.scope]
    if any(
        not scope or scope == "." or scope == ".." or scope.startswith("../")
        for scope in scopes
    ):
        fail("--scope must be a non-empty repository-relative path")
    paths = repository_paths(repo, scopes)
    if not paths:
        fail("scope matches no tracked or untracked-unignored files")
    files = []
    for rel in paths:
        cls, reason, lines = classify(rel, repo, overrides)
        treatment = (
            "read"
            if cls in READ_CLASSES
            else "boundary"
            if cls in BOUNDARY_CLASSES
            else "listed"
        )
        files.append(
            {
                "path": rel,
                "class": cls,
                "treatment": treatment,
                "lines": lines,
                "sha256": digest(repo / rel)
                if (repo / rel).is_file() and not (repo / rel).is_symlink()
                else None,
                "reason": reason,
            }
        )
    rubric = Path(__file__).resolve().parents[1] / "references" / "rubric.md"
    inventory = {
        "schema_version": 1,
        "repo": str(repo),
        "head": git(repo, "rev-parse", "HEAD").strip(),
        "branch": git(repo, "branch", "--show-current").strip(),
        "dirty": git(repo, "status", "--porcelain").splitlines(),
        "scope": scopes,
        "rubric": str(rubric),
        "properties": rubric_properties(rubric),
        "files": files,
    }
    readable = [item for item in files if item["treatment"] == "read"]
    shards = plan_shards(readable, args.shard_lines)
    dump(work / "inventory.json", inventory)
    dump(work / "shards.json", {"shards": shards})
    (work / "shards").mkdir(parents=True, exist_ok=True)
    counts = Counter(item["class"] for item in files)
    print(
        "classes: "
        + " · ".join(f"{cls} {counts[cls]}" for cls in CLASS_ORDER if counts[cls])
    )
    for item in files:
        if item["treatment"] != "read":
            print(f"exclude: {item['class']:9} {item['path']} ({item['reason']})")
    print(
        f"inventory: {len(files)} files, {sum(item['lines'] for item in files):,} lines; {len(readable)} read in full; {len(shards)} shards"
    )


def command_prompt(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    shards = load(work / "shards.json")["shards"]
    shard = next((item for item in shards if item["id"] == args.shard), None)
    if shard is None:
        fail(f"unknown shard {args.shard}")
    by_path = {item["path"]: item for item in inventory["files"]}
    files = "\n".join(
        f"- {path} ({by_path[path]['class']}, {by_path[path]['lines']} lines)"
        for path in shard["files"]
    )
    properties = "\n".join(f"- {name}" for name in inventory["properties"])
    rubric = Path(inventory["rubric"]).read_text()
    artifact = work / "shards" / f"{shard['id']}.json"
    print(f"""You are shard {shard["id"]} of {len(shards)} in a read-only test audit of `{inventory["repo"]}`.
Read every assigned file in full and write only `{artifact}`. Read
`{Path(__file__).resolve().parents[1] / "references" / "artifacts.md"}` before writing it.

For every file, enumerate all test cases, including tests embedded in production files, and
identify consequential production risk surfaces. A test needs a concrete regression; a risk
surface needs a plausible failure, impact, and coverage decision. Search the repository to
confirm production links, overlap, and named test evidence. Do not infer value from test
counts or coverage percentages.

Copy every property below into `properties_checked`:
{properties}

Assigned files:
{files}

Rubric:
{rubric}""")


def normalized(value):
    return " ".join(str(value).split())


def validate_finding(raw, inventory, properties, problems):
    finding = dict(raw)
    path = finding.get("path")
    line = finding.get("line")
    if finding.get("kind") not in FINDING_KINDS:
        problems.append(f"finding at {path}:{line} has invalid kind")
    if finding.get("severity") not in SEVERITIES:
        problems.append(f"finding at {path}:{line} has invalid severity")
    if finding.get("property") not in properties:
        problems.append(f"finding at {path}:{line} has unknown property")
    by_path = {item["path"]: item for item in inventory["files"]}
    if (
        path not in by_path
        or not isinstance(line, int)
        or line < 1
        or line > max(1, by_path.get(path, {}).get("lines", 0))
    ):
        problems.append(f"finding has invalid evidence location {path}:{line}")
        return finding
    for related in finding.get("related_paths", []):
        if related not in by_path:
            problems.append(
                f"finding at {path}:{line} names unknown related path {related}"
            )
    if not finding.get("observation") or not finding.get("recommendation"):
        problems.append(
            f"finding at {path}:{line} needs observation and recommendation"
        )
    evidence = normalized(finding.get("evidence", ""))
    source = (Path(inventory["repo"]) / path).read_text(errors="replace").splitlines()
    window = normalized("\n".join(source[max(0, line - 3) : line + 2]))
    if not evidence or evidence not in window:
        problems.append(f"finding evidence not found near {path}:{line}")
    return finding


def validate_assessment(raw, expected, inventory, findings, problems):
    path = raw.get("path")
    if path not in expected:
        problems.append(f"assessment names unassigned path {path}")
        return
    if raw.get("lines") != expected[path]["lines"]:
        problems.append(f"assessment line count differs for {path}")
    cases = raw.get("test_cases")
    surfaces = raw.get("risk_surfaces")
    if not isinstance(cases, list) or not isinstance(surfaces, list):
        problems.append(
            f"assessment for {path} needs test_cases and risk_surfaces arrays"
        )
        return
    if not cases and not raw.get("no_test_cases_reason"):
        problems.append(f"assessment for {path} needs no_test_cases_reason")
    if cases and raw.get("no_test_cases_reason"):
        problems.append(f"assessment for {path} has test cases and a no-test reason")
    if not surfaces and not raw.get("no_risk_surfaces_reason"):
        problems.append(f"assessment for {path} needs no_risk_surfaces_reason")
    if surfaces and raw.get("no_risk_surfaces_reason"):
        problems.append(
            f"assessment for {path} has risk surfaces and a no-surface reason"
        )
    inventory_paths = {item["path"] for item in inventory["files"]}
    case_lines = []
    for case in cases:
        line = case.get("line")
        production = case.get("production")
        overlap = case.get("overlap")
        if (
            not isinstance(line, int)
            or line < 1
            or line > max(1, expected[path]["lines"])
        ):
            problems.append(f"test case in {path} has invalid line {line}")
        if not case.get("name") or not case.get("regression") or not case.get("reason"):
            problems.append(
                f"test case at {path}:{line} needs name, regression, and reason"
            )
        if (
            case.get("risk") not in TEST_RISK
            or case.get("verdict") not in TEST_VERDICTS
        ):
            problems.append(f"test case at {path}:{line} has invalid risk or verdict")
        if case.get("verdict") == "keep" and case.get("risk") == "none":
            problems.append(f"kept test at {path}:{line} cannot have risk none")
        if not isinstance(production, list) or not isinstance(overlap, list):
            problems.append(
                f"test case at {path}:{line} needs production and overlap arrays"
            )
            production, overlap = [], []
        if case.get("verdict") == "keep" and not production:
            problems.append(f"kept test at {path}:{line} names no production path")
        case_lines.append(line)
        for linked in production + overlap:
            linked_path = linked.split(":", 1)[0]
            if linked_path not in inventory_paths:
                problems.append(
                    f"test case at {path}:{line} names unknown path {linked}"
                )
        if case.get("verdict") != "keep" and not any(
            finding.get("kind") in {"bloat", "false-confidence"}
            and finding.get("path") == path
            and abs(finding.get("line", -99) - line) <= 2
            for finding in findings
        ):
            problems.append(
                f"non-keep test at {path}:{line} needs a nearby bloat or false-confidence finding"
            )
    if len(case_lines) != len(set(case_lines)):
        problems.append(f"assessment for {path} repeats a test-case line")
    for surface in surfaces:
        line = surface.get("line")
        tests = surface.get("tests")
        if (
            not isinstance(line, int)
            or line < 1
            or line > max(1, expected[path]["lines"])
        ):
            problems.append(f"risk surface in {path} has invalid line {line}")
        if (
            not surface.get("behavior")
            or not surface.get("failure")
            or not surface.get("reason")
        ):
            problems.append(
                f"risk surface at {path}:{line} needs behavior, failure, and reason"
            )
        if (
            surface.get("impact") not in IMPACTS
            or surface.get("coverage") not in COVERAGE
        ):
            problems.append(
                f"risk surface at {path}:{line} has invalid impact or coverage"
            )
        if not isinstance(tests, list):
            problems.append(f"risk surface at {path}:{line} needs a tests array")
            tests = []
        if surface.get("coverage") == "covered" and not tests:
            problems.append(f"covered surface at {path}:{line} names no tests")
        if surface.get("coverage") in {"partial", "missing"} and not any(
            finding.get("kind") == "gap"
            and finding.get("path") == path
            and abs(finding.get("line", -99) - line) <= 2
            for finding in findings
        ):
            problems.append(
                f"{surface.get('coverage')} surface at {path}:{line} needs a nearby gap finding"
            )


def command_verify(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    shards = load(work / "shards.json")["shards"]
    properties = inventory["properties"]
    problems = []
    assessments = []
    findings = []
    read_paths = set()
    skipped_paths = set()
    pending = []
    repo = Path(inventory["repo"])
    if git(repo, "rev-parse", "HEAD").strip() != inventory["head"]:
        problems.append("repository HEAD changed since inventory")
    if set(repository_paths(repo, inventory["scope"])) != {
        item["path"] for item in inventory["files"]
    }:
        problems.append("repository file inventory changed since inventory")
    for item in inventory["files"]:
        path = repo / item["path"]
        if item["sha256"] and (
            not path.is_file() or path.is_symlink() or digest(path) != item["sha256"]
        ):
            problems.append(f"repository file changed since inventory: {item['path']}")
    for shard in shards:
        path = work / "shards" / f"{shard['id']}.json"
        if not path.exists():
            pending.append(shard["id"])
            continue
        artifact = load(path)
        if artifact.get("shard") != shard["id"]:
            problems.append(f"{path.name} declares the wrong shard")
        if artifact.get("properties_checked") != properties:
            problems.append(f"{path.name} does not list every rubric property in order")
        expected = {
            item["path"]: item
            for item in inventory["files"]
            if item["path"] in shard["files"]
        }
        artifact_findings = [
            validate_finding(item, inventory, properties, problems)
            for item in artifact.get("findings", [])
        ]
        local_assessments = artifact.get("assessments", [])
        local_paths = [item.get("path") for item in local_assessments]
        skipped_records = artifact.get("files_skipped", [])
        skipped = [item.get("path") for item in skipped_records]
        for item in skipped_records:
            if not item.get("reason"):
                problems.append(
                    f"{path.name} skips {item.get('path')} without a reason"
                )
        if len(local_paths) != len(set(local_paths)):
            problems.append(f"{path.name} assesses a file more than once")
        if set(local_paths) | set(skipped) != set(expected) or set(local_paths) & set(
            skipped
        ):
            problems.append(f"{path.name} does not account for its exact assignment")
        for item in local_assessments:
            validate_assessment(item, expected, inventory, artifact_findings, problems)
        assessments.extend(local_assessments)
        findings.extend(artifact_findings)
        read_paths.update(local_paths)
        skipped_paths.update(skipped)
    main_path = work / "shards" / "main.json"
    if main_path.exists():
        main = load(main_path)
        if main.get("shard") != "main" or main.get("properties_checked") != properties:
            problems.append("main.json has an invalid shard or property list")
        if main.get("assessments") or main.get("files_skipped"):
            problems.append("main.json must not claim file assessments")
        findings.extend(
            validate_finding(item, inventory, properties, problems)
            for item in main.get("findings", [])
        )
    identities = set()
    ordered_findings = []
    for finding in sorted(
        findings,
        key=lambda item: (
            item.get("kind", ""),
            item.get("path", ""),
            item.get("line", 0),
            item.get("property", ""),
        ),
    ):
        identity = (
            finding.get("kind"),
            finding.get("path"),
            finding.get("line"),
            finding.get("property"),
            finding.get("evidence"),
        )
        if identity in identities:
            continue
        identities.add(identity)
        finding["id"] = f"F-{len(ordered_findings) + 1:03d}"
        ordered_findings.append(finding)
    if pending:
        problems.append("pending shards: " + ", ".join(pending))
    if skipped_paths:
        problems.append("skipped files: " + ", ".join(sorted(skipped_paths)))
    readable = {
        item["path"] for item in inventory["files"] if item["treatment"] == "read"
    }
    if read_paths != readable:
        problems.append("read coverage does not equal the maintained-file inventory")
    test_refs = {
        f"{assessment['path']}:{case['line']}"
        for assessment in assessments
        for case in assessment.get("test_cases", [])
    }
    for assessment in assessments:
        for surface in assessment.get("risk_surfaces", []):
            if surface.get("coverage") in {"covered", "partial"}:
                references = surface.get("tests", [])
                if not isinstance(references, list):
                    continue
                for reference in references:
                    if reference not in test_refs:
                        problems.append(
                            f"surface at {assessment['path']}:{surface.get('line')} names unknown test {reference}"
                        )
    ledger = {
        "schema_version": 1,
        "inventory": inventory,
        "assessments": assessments,
        "findings": ordered_findings,
        "problems": problems,
    }
    dump(work / "ledger.json", ledger)
    print(
        f"coverage: {len(read_paths)}/{len(readable)} maintained files read; {len(ordered_findings)} findings; {len(problems)} problems"
    )
    if problems:
        for problem in problems:
            print(f"problem: {problem}")
        raise SystemExit(1)


def score(assessments):
    cases = [case for item in assessments for case in item.get("test_cases", [])]
    surfaces = [
        surface for item in assessments for surface in item.get("risk_surfaces", [])
    ]
    scored_surfaces = [
        surface for surface in surfaces if surface["coverage"] in COVERAGE_CREDIT
    ]
    coverage_weight = sum(
        IMPACT_WEIGHT[surface["impact"]] for surface in scored_surfaces
    )
    coverage = (
        None
        if not coverage_weight
        else round(
            100
            * sum(
                IMPACT_WEIGHT[surface["impact"]] * COVERAGE_CREDIT[surface["coverage"]]
                for surface in scored_surfaces
            )
            / coverage_weight
        )
    )
    signal = (
        None
        if not cases
        else round(
            100 * sum(SIGNAL_CREDIT[case["verdict"]] for case in cases) / len(cases)
        )
    )
    return coverage, signal, cases, surfaces


def escaped(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def command_render(args):
    work = Path(args.work)
    ledger = load(work / "ledger.json")
    if ledger.get("problems"):
        fail("ledger has verification problems; rerun verify")
    narrative = load(work / "narrative.json")
    if not narrative.get("verdict") or not narrative.get("method"):
        fail("narrative.json needs verdict and method")
    inventory = ledger["inventory"]
    output = Path(args.out).resolve()
    repo = Path(inventory["repo"]).resolve()
    if output == repo or repo in output.parents:
        fail("report destination must be outside the audited repository")
    coverage, signal, cases, surfaces = score(ledger["assessments"])
    findings = ledger["findings"]
    case_counts = Counter(case["verdict"] for case in cases)
    surface_counts = Counter(surface["coverage"] for surface in surfaces)
    lines = [
        "# Test audit",
        "",
        narrative["verdict"],
        "",
        f"- Repository: `{inventory['repo']}`",
        f"- Commit: `{inventory['head']}`",
        f"- Scope: `{', '.join(inventory['scope']) if inventory['scope'] else 'whole repository'}`",
        f"- Method: {narrative['method']}",
        "",
        "## Results",
        "",
        f"- Risk coverage: **{coverage if coverage is not None else 'n/a'}** / 100",
        f"- Test signal: **{signal if signal is not None else 'n/a'}** / 100",
        "- Production surfaces: "
        + ", ".join(
            f"{name} {surface_counts[name]}" for name in sorted(surface_counts)
        ),
        "- Existing tests: "
        + ", ".join(f"{name} {case_counts[name]}" for name in sorted(case_counts)),
        "",
        "The scores are independent: strength on one axis does not offset weakness on the other.",
    ]
    for title, kinds in (
        ("Coverage gaps", {"gap"}),
        ("Test bloat", {"bloat"}),
        ("False confidence", {"false-confidence"}),
    ):
        lines.extend(["", f"## {title}", ""])
        group = [finding for finding in findings if finding["kind"] in kinds]
        if not group:
            lines.append("None found.")
            continue
        for finding in group:
            lines.extend(
                [
                    f"### {finding['id']} · {finding['severity']} · `{finding['path']}:{finding['line']}`",
                    "",
                    finding["observation"],
                    "",
                    f"Property: {finding['property']}",
                    "",
                    f"Evidence: `{escaped(finding['evidence'])}`",
                    "",
                    f"Recommendation: {finding['recommendation']}",
                    "",
                ]
            )
            if finding.get("related_paths"):
                lines.extend(
                    [
                        "Related: "
                        + ", ".join(
                            f"`{escaped(path)}`" for path in finding["related_paths"]
                        ),
                        "",
                    ]
                )
    lines.extend(
        [
            "",
            "## Risk-surface ledger",
            "",
            "| Production | Impact | Coverage | Failure | Tests |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for assessment in ledger["assessments"]:
        for surface in assessment.get("risk_surfaces", []):
            tests = ", ".join(surface.get("tests", [])) or "—"
            lines.append(
                f"| `{escaped(assessment['path'])}:{surface['line']}` | {surface['impact']} | "
                f"{surface['coverage']} | {escaped(surface['failure'])} | {escaped(tests)} |"
            )
    lines.extend(
        [
            "",
            "## Test ledger",
            "",
            "| Test | Risk | Verdict | Regression | Production |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for assessment in ledger["assessments"]:
        for case in assessment.get("test_cases", []):
            production = ", ".join(case.get("production", [])) or "—"
            lines.append(
                f"| `{escaped(assessment['path'])}:{case['line']}` {escaped(case['name'])} | "
                f"{case['risk']} | {case['verdict']} | {escaped(case['regression'])} | {escaped(production)} |"
            )
    by_path = {item["path"]: item for item in ledger["assessments"]}
    lines.extend(
        [
            "",
            "## File ledger",
            "",
            "| Path | Tests | Risk surfaces |",
            "| --- | ---: | ---: |",
        ]
    )
    for item in inventory["files"]:
        if item["treatment"] == "read":
            assessment = by_path[item["path"]]
            lines.append(
                f"| `{escaped(item['path'])}` | {len(assessment['test_cases'])} | {len(assessment['risk_surfaces'])} |"
            )
        else:
            lines.append(f"| `{escaped(item['path'])}` ({item['treatment']}) | — | — |")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n")
    print(
        f"report: {output}; risk coverage {coverage if coverage is not None else 'n/a'}; test signal {signal if signal is not None else 'n/a'}; {len(findings)} findings"
    )


def command_card(args):
    ledger = load(Path(args.work) / "ledger.json")
    if ledger.get("problems"):
        fail("ledger has verification problems")
    coverage, signal, cases, surfaces = score(ledger["assessments"])
    findings = Counter(item["kind"] for item in ledger["findings"])
    print("                              TEST AUDIT")
    print()
    print(f"  Risk coverage   {coverage if coverage is not None else 'n/a':>3} / 100")
    print(f"  Test signal     {signal if signal is not None else 'n/a':>3} / 100")
    print()
    print(f"  Evidence        {len(surfaces)} risk surfaces · {len(cases)} tests")
    print(
        f"  Findings        {findings['gap']} gaps · {findings['bloat']} bloat · {findings['false-confidence']} false confidence"
    )
    print()
    print(f"Detailed audit   {Path(args.report).resolve()}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    inventory = commands.add_parser("inventory")
    inventory.add_argument("--repo", default=".")
    inventory.add_argument("--work", required=True)
    inventory.add_argument("--scope", action="append", default=[])
    inventory.add_argument("--override", action="append", default=[])
    inventory.add_argument("--shard-lines", type=int, default=8000)
    inventory.set_defaults(function=command_inventory)
    prompt = commands.add_parser("prompt")
    prompt.add_argument("--work", required=True)
    prompt.add_argument("--shard", required=True)
    prompt.set_defaults(function=command_prompt)
    verify = commands.add_parser("verify")
    verify.add_argument("--work", required=True)
    verify.set_defaults(function=command_verify)
    render = commands.add_parser("render")
    render.add_argument("--work", required=True)
    render.add_argument("--out", required=True)
    render.set_defaults(function=command_render)
    card = commands.add_parser("card")
    card.add_argument("--work", required=True)
    card.add_argument("--report", required=True)
    card.set_defaults(function=command_card)
    args = parser.parse_args()
    args.function(args)


if __name__ == "__main__":
    main()
