#!/usr/bin/env python3
"""Mechanical half of the audit-greppability skill.

The model judges; this script enumerates, assigns, reconciles, measures, and renders, so every
count in the report comes from a file on disk rather than from memory. Subcommands run in this
order: inventory, shard-prompt, verify, measure, render. All artifacts live in one work directory
outside the audited repository. Requires git and Python 3; nothing else.
"""

import argparse
import json
import re
import subprocess
import sys
import textwrap
from collections import Counter, defaultdict
from pathlib import Path

READ_CLASSES = ("source", "test", "config", "script", "schema", "docs")
BOUNDARY_CLASSES = ("generated", "vendored")
LISTED_CLASSES = ("data", "binary")
CLASS_ORDER = READ_CLASSES + BOUNDARY_CLASSES + LISTED_CLASSES
SEVERITIES = ("HIGH", "MED", "LOW")
DEFAULT_SHARD_LINES = 10000
MAX_SHARD_FILES = 400
REPORT_WIDTH = 100

VENDOR_SEGMENTS = {"vendor", "vendored", "third_party", "third-party", "node_modules", "extern", "external"}
GENERATED_SEGMENTS = {"generated", "__generated__", "gen", "dist", "build"}
GENERATED_NAME = re.compile(r"(\.pb\.|_pb2(_grpc)?\.py$|\.min\.(js|css)$|\.generated\.|\.g\.dart$)")
GENERATED_MARKER = re.compile(r"(@generated|do not edit|auto-?generated|generated by)", re.I)
DATA_SEGMENTS = {"fixtures", "fixture", "__fixtures__", "testdata", "snapshots", "__snapshots__"}
DATA_NAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "cargo.lock", "gemfile.lock",
    "composer.lock", "go.sum", "uv.lock", "pipfile.lock", "bun.lockb",
}
DATA_PREFIXES = ("license", "notice", "copying")
DATA_EXT = {".csv", ".tsv", ".parquet", ".jsonl", ".ndjson", ".svg", ".snap", ".lock", ".pdf"}
TEST_SEGMENTS = {"test", "tests", "spec", "specs", "__tests__", "e2e"}
TEST_NAME = re.compile(r"(^test_.*\.py$|_test\.[^.]+$|\.test\.[^.]+$|\.spec\.[^.]+$|^conftest\.py$)")
SCHEMA_SEGMENTS = {"migrations", "migration", "schema", "schemas"}
SCHEMA_EXT = {".sql", ".prisma", ".graphql", ".gql", ".proto", ".avsc", ".thrift", ".xsd"}
CONFIG_NAMES = {"dockerfile", "procfile", "codeowners", ".env.example", ".editorconfig", ".gitattributes", ".gitignore", ".npmrc", ".nvmrc"}
CONFIG_EXT = {".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".properties", ".tf", ".hcl"}
SCRIPT_NAMES = {"makefile", "justfile", "rakefile"}
SCRIPT_SEGMENTS = {"scripts", "script", "bin", "tools"}
SCRIPT_EXT = {".sh", ".bash", ".zsh", ".fish", ".ps1", ".bat", ".cmd"}
DOC_EXT = {".md", ".mdx", ".rst", ".txt", ".adoc", ".asciidoc"}


# --- helpers -------------------------------------------------------------------------------


def git(repo, *args, check=True):
    result = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True)
    if check and result.returncode not in (0, 1):
        sys.exit(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def load(path, default=None):
    path = Path(path)
    if not path.exists():
        if default is not None:
            return default
        sys.exit(f"missing {path}")
    return json.loads(path.read_text())


def dump(path, value):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(value, indent=1, sort_keys=True) + "\n")


def rubric_headings(rubric_path):
    text = Path(rubric_path).read_text()
    headings = [line[4:].strip() for line in text.splitlines() if line.startswith("### ")]
    if not headings:
        sys.exit(f"no '### ' properties found in {rubric_path}")
    return headings


def rubric_body(rubric_path):
    """The rubric without its skill frontmatter, so shards see the properties and nothing else."""
    text = Path(rubric_path).read_text()
    if text.startswith("---"):
        text = text.split("\n---\n", 1)[1]
    return text.strip()


def default_rubric():
    return Path(__file__).resolve().parent.parent.parent / "greppable" / "SKILL.md"


def ascii_safe(text):
    return str(text).encode("ascii", "backslashreplace").decode("ascii")


def bar(value, unit, width=40):
    """Scaled bar: one '#' per `unit`, rounded up so any nonzero value shows one mark."""
    if value <= 0 or unit <= 0:
        return ""
    return "#" * min(width, max(1, round(value / unit)))


def fmt(n):
    return f"{n:,}"


def wrap(text, width=REPORT_WIDTH, indent=""):
    return textwrap.fill(" ".join(text.split()), width=width, subsequent_indent=indent, break_long_words=False, break_on_hyphens=False)


def field(label, text, gutter=2, label_width=9):
    """One labelled report line, wrapped under the value column: `  label     text...`."""
    first = " " * gutter + f"{label:{label_width}} "
    return textwrap.fill(" ".join(str(text).split()), width=REPORT_WIDTH, initial_indent=first,
                         subsequent_indent=" " * len(first), break_long_words=False, break_on_hyphens=False)


# --- inventory -----------------------------------------------------------------------------


def classify(rel, repo, attrs, overrides):
    path = Path(rel)
    name = path.name.lower()
    segments = {segment.lower() for segment in path.parts[:-1]}
    ext = path.suffix.lower()
    full = repo / rel
    try:
        head = full.open("rb").read(8192)
    except OSError as error:
        return "binary", f"unreadable: {error.strerror}", 0
    if b"\0" in head:
        return "binary", "binary content", 0
    lines = full.read_bytes().count(b"\n")
    first = head.decode("utf-8", "replace").splitlines()[:8]
    for prefix, cls in overrides:
        if rel == prefix or rel.startswith(prefix.rstrip("/") + "/"):
            return cls, f"--override {prefix}={cls}", lines
    attr = attrs.get(rel, {})
    if attr.get("linguist-vendored") == "true" or segments & VENDOR_SEGMENTS:
        return "vendored", "vendored directory or linguist-vendored", lines
    if attr.get("linguist-generated") == "true":
        return "generated", "linguist-generated attribute", lines
    if segments & GENERATED_SEGMENTS or GENERATED_NAME.search(name):
        return "generated", "generated path or name pattern", lines
    if any(GENERATED_MARKER.search(line) for line in first):
        return "generated", "generated marker in header", lines
    if name in DATA_NAMES or name.startswith(DATA_PREFIXES) or ext in DATA_EXT:
        return "data", "lockfile, license, notice, or data format", lines
    if segments & DATA_SEGMENTS:
        return "data", "fixture or snapshot: name assessed, content not read", lines
    if segments & TEST_SEGMENTS or TEST_NAME.search(name):
        return "test", "", lines
    if segments & SCHEMA_SEGMENTS or ext in SCHEMA_EXT or name.startswith("schema."):
        return "schema", "", lines
    if name in CONFIG_NAMES or name.startswith("dockerfile") or name.startswith("requirements") and ext == ".txt":
        return "config", "", lines
    if ext in CONFIG_EXT or (len(path.parts) == 1 and name.startswith(".")):
        return "config", "", lines
    if name in SCRIPT_NAMES or ext in SCRIPT_EXT or segments & SCRIPT_SEGMENTS:
        return "script", "", lines
    if ext in DOC_EXT or name.startswith("changelog"):
        return "docs", "", lines
    return "source", "", lines


def read_attrs(repo, paths):
    out = subprocess.run(
        ["git", "-C", str(repo), "check-attr", "linguist-generated", "linguist-vendored", "--stdin"],
        input="\n".join(paths), capture_output=True, text=True,
    ).stdout
    attrs = defaultdict(dict)
    for line in out.splitlines():
        parts = line.rsplit(": ", 2)
        if len(parts) == 3:
            attrs[parts[0]][parts[1]] = parts[2]
    return attrs


def plan_shards(files, shard_lines):
    """Directory-contiguous shards balanced by line count, so neighbours are read together."""
    by_path = {f["path"]: f["lines"] for f in files}
    groups, current, current_lines = [], [], 0
    for path in sorted(by_path):
        if current and (current_lines + by_path[path] > shard_lines or len(current) >= MAX_SHARD_FILES):
            groups.append(current)
            current, current_lines = [], 0
        current.append(path)
        current_lines += by_path[path]
    if current:
        groups.append(current)
    return [
        {"id": f"S-{index:02d}", "files": paths, "lines": sum(by_path[p] for p in paths), "status": "pending", "parent": None}
        for index, paths in enumerate(groups, 1)
    ]


def cmd_inventory(args):
    repo = Path(git(args.repo, "rev-parse", "--show-toplevel").strip() or sys.exit("not a git repository"))
    work = Path(args.work)
    if work.resolve().is_relative_to(repo.resolve()):
        sys.exit("work directory must live outside the audited repository")
    work.mkdir(parents=True, exist_ok=True)
    tracked = git(repo, "ls-files", "-z").split("\0")
    untracked = git(repo, "ls-files", "-z", "--others", "--exclude-standard").split("\0")
    paths = sorted({p for p in tracked + untracked if p})
    scope = [s.strip("/") for s in args.scope]
    if scope:
        paths = [p for p in paths if any(p == s or p.startswith(s + "/") for s in scope)]
    attrs = read_attrs(repo, paths)
    overrides = []
    for item in args.override:
        prefix, _, cls = item.partition("=")
        if cls not in CLASS_ORDER:
            sys.exit(f"--override class must be one of {', '.join(CLASS_ORDER)}")
        overrides.append((prefix, cls))
    files = []
    for rel in paths:
        if not (repo / rel).is_file():
            continue
        cls, reason, lines = classify(rel, repo, attrs, overrides)
        treatment = "read" if cls in READ_CLASSES else "boundary" if cls in BOUNDARY_CLASSES else "listed"
        files.append({"path": rel, "class": cls, "treatment": treatment, "lines": lines, "reason": reason})
    rubric = Path(args.rubric) if args.rubric else default_rubric()
    inventory = {
        "repo": str(repo),
        "origin": git(repo, "remote", "get-url", "origin", check=False).strip(),
        "head": git(repo, "rev-parse", "HEAD").strip(),
        "branch": git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip(),
        "dirty": git(repo, "status", "--porcelain").splitlines(),
        "scope": scope,
        "rubric": str(rubric),
        "properties": rubric_headings(rubric),
        "shard_lines": args.shard_lines,
        "files": files,
    }
    dump(work / "inventory.json", inventory)
    shards = plan_shards([f for f in files if f["treatment"] == "read"], args.shard_lines)
    dump(work / "shards.json", {"shards": shards})
    (work / "shards").mkdir(exist_ok=True)
    print(coverage_table(inventory, None))
    print()
    print(exclusion_table(files))
    print()
    print(f"SHARD PLAN  {len(shards)} shards, <= {fmt(args.shard_lines)} lines and <= {MAX_SHARD_FILES} files each")
    for shard in shards:
        first, last = shard["files"][0], shard["files"][-1]
        print(f"  {shard['id']}  {len(shard['files']):4d} files  {fmt(shard['lines']):>8} lines  {first} .. {last}")
    print(f"\nproperties: {len(inventory['properties'])} from {rubric}")


# --- shard prompt --------------------------------------------------------------------------


def cmd_shard_prompt(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    shards = load(work / "shards.json")["shards"]
    shard = next((s for s in shards if s["id"] == args.shard), None) or sys.exit(f"unknown shard {args.shard}")
    template = (Path(__file__).resolve().parent.parent / "references" / "shard-prompt.md").read_text()
    by_path = {f["path"]: f for f in inventory["files"]}
    files = "\n".join(f"- {p} ({by_path[p]['class']}, {by_path[p]['lines']} lines)" for p in shard["files"])
    vocabulary = load(work / "vocabulary.json", {"concepts": []})["concepts"]
    vocab = "\n".join(f"- {c['concept']}: {', '.join(c['spellings'])}" for c in vocabulary) or "- (none recorded yet)"
    filled = (
        template.replace("{{SHARD_ID}}", shard["id"])
        .replace("{{SHARD_COUNT}}", str(len(shards)))
        .replace("{{REPO}}", inventory["repo"])
        .replace("{{ARTIFACT}}", str(work / "shards" / f"{shard['id']}.json"))
        .replace("{{PROPERTIES}}", "\n".join(f"- {h}" for h in inventory["properties"]))
        .replace("{{VOCABULARY}}", vocab)
        .replace("{{FILES}}", files)
        .replace("{{RUBRIC}}", rubric_body(inventory["rubric"]))
    )
    print(filled)


# --- verify --------------------------------------------------------------------------------


def check_accept(checks):
    if not isinstance(checks, list) or not checks:
        return "accept must be a non-empty list"
    for check in checks:
        argv = check.get("argv") if isinstance(check, dict) else None
        if not isinstance(argv, list) or not argv or not all(isinstance(a, str) for a in argv):
            return "accept entries need an argv list of strings"
        if not isinstance(check.get("expect"), str) or not check["expect"]:
            return "accept entries need an expect string"
    return None


def check_finding(finding, index, inventory, repo, properties):
    required = ("property", "severity", "path", "line", "evidence", "observation")
    missing = [k for k in required if k not in finding]
    if missing:
        return f"finding {index}: missing {', '.join(missing)}"
    if finding["property"].strip() not in properties:
        return f"finding {index}: property is not a rubric heading: {finding['property']!r}"
    if finding["severity"] not in SEVERITIES:
        return f"finding {index}: severity must be one of {SEVERITIES}"
    if bool(finding.get("recipe")) == bool(finding.get("decision")):
        return f"finding {index}: needs exactly one of recipe (list of steps) or decision (question and options)"
    if not finding.get("accept") and not finding.get("symbol"):
        return f"finding {index}: needs accept checks or a symbol to derive them from"
    if finding.get("accept") and (error := check_accept(finding["accept"])):
        return f"finding {index}: {error}"
    if finding["path"] not in inventory:
        return f"finding {index}: {finding['path']} is not in the inventory"
    file = repo / finding["path"]
    if not file.is_file():
        return f"finding {index}: {finding['path']} does not exist"
    lines = file.read_text(errors="replace").splitlines()
    line = finding["line"]
    if not isinstance(line, int) or line < 1 or line > len(lines):
        return f"finding {index}: {finding['path']}:{line} is out of range (1..{len(lines)})"
    quote = next((q.strip() for q in str(finding["evidence"]).splitlines() if q.strip()), "")
    window = lines[max(0, line - 3): line + 2]
    if not quote or not any(quote in candidate for candidate in window):
        return f"finding {index}: evidence not found at {finding['path']}:{line} (+/-2 lines)"
    return None


def cmd_verify(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    repo = Path(inventory["repo"])
    by_path = {f["path"]: f for f in inventory["files"]}
    properties = set(inventory["properties"])
    shard_file = work / "shards.json"
    shards = load(shard_file)["shards"]
    redispatch = {s["parent"] for s in shards if s["parent"]}
    status = {}
    for f in inventory["files"]:
        status[f["path"]] = {"read": "pending", "boundary": "boundary-only", "listed": "listed"}[f["treatment"]]
    reader = {}
    findings, dropped, leads, vocab_additions, problems, undeclared_by_shard = [], [], [], [], [], {}
    new_shards = []
    for shard in shards:
        # Coverage is recomputed from the artifacts present and valid right now, never from a
        # status persisted by an earlier verify.
        shard["status"] = "pending"
        artifact = work / "shards" / f"{shard['id']}.json"
        if not artifact.exists():
            continue
        try:
            data = json.loads(artifact.read_text())
        except json.JSONDecodeError as error:
            problems.append(f"{shard['id']}: artifact is not valid JSON ({error})")
            continue
        assigned = set(shard["files"])
        read = {e["path"] for e in data.get("files_read", []) if isinstance(e, dict)}
        undeclared = sorted(properties - {str(h).strip() for h in data.get("properties_checked", [])})
        if undeclared:
            undeclared_by_shard[shard["id"]] = f"{shard['id']}: properties not declared checked, files not counted as read: {', '.join(undeclared)}"
            read = set()
        skipped = {e["path"]: e.get("reason", "") for e in data.get("files_skipped", []) if isinstance(e, dict)}
        extra = (read | set(skipped)) - assigned
        if extra:
            problems.append(f"{shard['id']}: reported files outside its assignment: {', '.join(sorted(extra))}")
        remainder = sorted((assigned - read) | (set(skipped) & assigned))
        for p in read & assigned:
            status[p], reader[p] = "read-in-full", shard["id"]
        if remainder:
            if shard["id"] in redispatch or shard["parent"]:
                for p in remainder:
                    status[p] = "uncovered"
                    by_path[p]["reason"] = skipped.get(p) or f"not read by {shard['id']} after re-dispatch"
            else:
                child = {"id": f"{shard['id']}r", "files": remainder, "lines": sum(by_path[p]["lines"] for p in remainder),
                         "status": "pending", "parent": shard["id"]}
                if not any(s["id"] == child["id"] for s in shards):
                    new_shards.append(child)
        for index, finding in enumerate(data.get("findings", []), 1):
            error = check_finding(finding, index, by_path, repo, properties)
            if error:
                dropped.append({"shard": shard["id"], "reason": error, "path": finding.get("path"), "line": finding.get("line")})
            else:
                findings.append({**finding, "property": finding["property"].strip(), "shard": shard["id"]})
        leads.extend({**lead, "shard": shard["id"]} for lead in data.get("cross_shard_leads", []))
        vocab_additions.extend({**v, "shard": shard["id"]} for v in data.get("vocabulary_additions", []))
        shard["status"] = "reconciled" if not remainder else "partial"
    main_artifact = work / "shards" / "main.json"
    if main_artifact.exists():
        try:
            data = json.loads(main_artifact.read_text())
        except json.JSONDecodeError as error:
            problems.append(f"main: artifact is not valid JSON ({error})")
            data = {}
        for index, finding in enumerate(data.get("findings", []), 1):
            error = check_finding(finding, index, by_path, repo, properties)
            if error:
                dropped.append({"shard": "main", "reason": error, "path": finding.get("path"), "line": finding.get("line")})
            else:
                findings.append({**finding, "property": finding["property"].strip(), "shard": "main"})
    seen = {}
    unique = []
    for finding in findings:
        key = (finding["property"], finding["path"], finding["line"], str(finding["evidence"]).strip())
        if key in seen:
            dropped.append({"shard": finding["shard"], "path": finding["path"], "line": finding["line"],
                            "reason": f"duplicate of {seen[key]} finding at {finding['path']}:{finding['line']} for {finding['property']!r}"})
        else:
            seen[key] = finding["shard"]
            unique.append(finding)
    findings = unique
    shards.extend(new_shards)
    # A shard is reconciled once every assigned file has a final status, including through its child.
    for shard in shards:
        if shard["status"] != "pending" and all(status[p] != "pending" for p in shard["files"]):
            shard["status"] = "reconciled"
    recovered = []
    for shard in shards:
        message = undeclared_by_shard.get(shard["id"])
        if message:
            (recovered if all(status[p] == "read-in-full" for p in shard["files"]) else problems).append(message)
    dump(shard_file, {"shards": shards})
    findings.sort(key=lambda f: (f["path"], f["line"], f["property"]))
    for index, finding in enumerate(findings, 1):
        finding["id"] = f"F-{index:03d}"
    dirty_now = git(repo, "status", "--porcelain").splitlines()
    ledger = {
        "files": [{**f, "status": status[f["path"]], "reader": reader.get(f["path"])} for f in inventory["files"]],
        "findings": findings,
        "dropped": dropped,
        "problems": problems,
        "recovered": recovered,
        "cross_shard_leads": leads,
        "vocabulary_additions": vocab_additions,
        "git_status_delta": sorted(set(dirty_now) ^ set(inventory["dirty"])),
        "shards": shards,
    }
    dump(work / "ledger.json", ledger)
    print(progress_line(ledger))
    print()
    print("SHARDS")
    for shard in shards:
        print(f"  {shard['id']:6} {shard['status']:10} {len(shard['files']):4d} files  {fmt(shard['lines']):>8} lines"
              + (f"  parent {shard['parent']}" if shard["parent"] else ""))
    if new_shards:
        print("\nRE-DISPATCH (run shard-prompt for each, then verify again)")
        for shard in new_shards:
            print(f"  {shard['id']}  {len(shard['files'])} files")
    if problems:
        print("\nPROBLEMS")
        for p in problems:
            print(f"  {p}")
    if dropped:
        print("\nDROPPED FINDINGS")
        for d in dropped:
            print(f"  {d['shard']}: {d['reason']}")
    if ledger["git_status_delta"]:
        print("\nGIT STATUS CHANGED SINCE INVENTORY")
        for line in ledger["git_status_delta"]:
            print(f"  {line}")


def progress_line(ledger):
    files = ledger["files"]
    readable = [f for f in files if f["treatment"] == "read"]
    read = sum(f["status"] == "read-in-full" for f in readable)
    uncovered = sum(f["status"] == "uncovered" for f in readable)
    pending = sum(f["status"] == "pending" for f in readable)
    shards = ledger["shards"]
    done = sum(s["status"] == "reconciled" for s in shards)
    pct = f"{100 * read // len(readable)}%" if readable else "n/a"
    return (f"coverage: read {read}/{len(readable)} files ({pct}) | shards {done}/{len(shards)} reconciled"
            f" | pending files {pending} | uncovered {uncovered} | findings {len(ledger['findings'])}"
            f" (dropped {len(ledger['dropped'])})")


# --- measure -------------------------------------------------------------------------------


def grep_hits(repo, term, by_path):
    out = git(repo, "grep", "-nwI", "--", term)
    hits = []
    for line in out.splitlines():
        path, _, rest = line.partition(":")
        if path in by_path:
            hits.append(f"{path}:{rest.partition(':')[0]}")
    return hits


def cmd_measure(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    ledger = load(work / "ledger.json")
    repo = Path(inventory["repo"])
    by_path = {f["path"]: f for f in inventory["files"]}
    cls = lambda hit: by_path[hit.rsplit(":", 1)[0]]["class"]
    problems = ledger["measure_problems"] = []
    for finding in ledger["findings"]:
        symbol = finding.get("symbol")
        if symbol:
            hits = grep_hits(repo, symbol, by_path)
            finding["blast"] = {
                "symbol": symbol, "hits": len(hits), "files": len({h.rsplit(':', 1)[0] for h in hits}),
                "by_class": dict(Counter(cls(h) for h in hits)), "paths": hits,
            }
            new = finding.get("new_symbol")
            if new:
                finding["blast"]["new_symbol"] = new
                finding["blast"]["new_symbol_hits"] = len(grep_hits(repo, new, by_path))
            if not finding.get("accept"):
                finding["accept"] = [{"argv": ["git", "grep", "-nw", "--", new], "expect": "definition and every call site"}] if new else []
                finding["accept"].append({"argv": ["git", "grep", "-nw", "--", symbol], "expect": "0 hits" if new else "only the surviving owner"})
        elif not finding.get("accept"):
            finding["accept"] = []
    concepts = load(work / "vocabulary.json", {"concepts": []})["concepts"]
    trials = []
    for concept in concepts:
        per_spelling = {s: grep_hits(repo, s, by_path) for s in concept["spellings"]}
        reach = {}
        for key in ("owner", "wiring", "contract", "tests", "absence"):
            value = concept.get("reach", {}).get(key)
            if value in (None, ""):
                reach[key] = {"mark": " ", "path": None}
            elif value == "n/a":
                reach[key] = {"mark": "-", "path": None}
            elif value.split(":")[0] in by_path:
                reach[key] = {"mark": "x", "path": value}
            else:
                reach[key] = {"mark": "?", "path": value}
                problems.append(f"vocabulary: {concept['concept']} {key} path not in inventory: {value}")
        named = sorted({p for p in by_path for s in concept["spellings"] if s.lower() in p.lower()})
        trials.append({
            "concept": concept["concept"], "spellings": concept["spellings"], "reach": reach,
            "hits": sum(len(h) for h in per_spelling.values()),
            "hits_by_spelling": {s: len(h) for s, h in per_spelling.items()},
            "hits_by_class": dict(Counter(cls(h) for hits in per_spelling.values() for h in hits)),
            "named_files": named,
        })
    packets = load(work / "packets.json", {"packets": []})["packets"]
    ids = {f["id"]: f for f in ledger["findings"]}
    assigned = Counter()
    packet_ids = Counter(p["id"] for p in packets)
    for pid, n in sorted(packet_ids.items()):
        if n > 1:
            problems.append(f"packet {pid}: id used {n} times")
    for packet in packets:
        unknown = [fid for fid in packet["findings"] if fid not in ids]
        if unknown:
            problems.append(f"packet {packet['id']}: unknown findings {', '.join(unknown)}")
        if error := check_accept(packet.get("accept")):
            problems.append(f"packet {packet['id']}: {error}")
        assigned.update(packet["findings"])
        paths = {ids[fid]["path"] for fid in packet["findings"] if fid in ids}
        blast_paths = {h.rsplit(":", 1)[0] for fid in packet["findings"] if fid in ids for h in ids[fid].get("blast", {}).get("paths", [])}
        packet["files"] = sorted(paths | blast_paths)
        packet["tests"] = sorted(p for p in packet["files"] if by_path[p]["class"] == "test")
    unassigned = [fid for fid in ids if assigned[fid] == 0]
    duplicates = [fid for fid, n in assigned.items() if n > 1]
    if duplicates:
        problems.append(f"findings in more than one packet: {', '.join(duplicates)}")
    narrative = load(work / "narrative.json", {})
    clean = [p for p in inventory["properties"] if not any(f["property"] == p for f in ledger["findings"])
             and p not in narrative.get("properties_not_applicable", {})]
    for prop in clean:
        if not narrative.get("property_checks", {}).get(prop):
            problems.append(f"narrative: clean property has no property_checks evidence: {prop!r}")
    order = topological(packets)
    ledger["trials"] = trials
    ledger["packets"] = [next(p for p in packets if p["id"] == pid) for pid in order]
    ledger["unassigned_findings"] = unassigned
    dump(work / "ledger.json", ledger)
    print(f"measured: {sum('blast' in f for f in ledger['findings'])} blast radii, {len(trials)} search trials,"
          f" {len(packets)} packets ({len(unassigned)} findings unassigned); problems {len(problems)}")
    for problem in problems:
        print(f"  problem: {problem}")


def topological(packets):
    after = {p["id"]: list(p.get("after", [])) for p in packets}
    order, seen = [], set()

    def visit(pid, stack):
        if pid in seen:
            return
        if pid in stack:
            sys.exit(f"packet dependency cycle at {pid}")
        for dep in after.get(pid, []):
            if dep not in after:
                sys.exit(f"packet {pid} depends on unknown packet {dep}")
            visit(dep, stack | {pid})
        seen.add(pid)
        order.append(pid)

    for pid in sorted(after):
        visit(pid, frozenset())
    return order


# --- render --------------------------------------------------------------------------------


def coverage_table(inventory, ledger):
    files = ledger["files"] if ledger else inventory["files"]
    rows = []
    total_lines = sum(f["lines"] for f in files)
    unit = max(1, total_lines // 38) if total_lines else 1
    out = [f"COVERAGE                                              scale: one # = {fmt(unit)} lines"]
    out.append(f"  {'class':10} {'files':>6} {'lines':>9}  {'':38}  {'read':>5} {'bndry':>5} {'list':>5} {'uncov':>5} {'pend':>5}")
    for cls in CLASS_ORDER:
        group = [f for f in files if f["class"] == cls]
        if not group:
            continue
        lines = sum(f["lines"] for f in group)
        st = Counter(f.get("status", {"read": "pending", "boundary": "boundary-only", "listed": "listed"}[f["treatment"]]) for f in group)
        mark = bar(lines, unit, 38) if cls in READ_CLASSES else "." * len(bar(lines, unit, 38))
        out.append(f"  {cls:10} {len(group):6d} {fmt(lines):>9}  {mark:38}  {st['read-in-full']:5d} {st['boundary-only']:5d}"
                   f" {st['listed']:5d} {st['uncovered']:5d} {st['pending']:5d}")
        rows.append(cls)
    out.append(f"  {'total':10} {len(files):6d} {fmt(total_lines):>9}")
    out.append("  bars: '#' classes are read in full, '.' classes are boundary-checked or listed only")
    return "\n".join(out)


def exclusion_table(files):
    out = ["EXCLUSIONS  (not read in full; every count is from the inventory)"]
    groups = defaultdict(list)
    for f in files:
        if f["treatment"] != "read":
            groups[(f["class"], f["reason"])].append(f)
    if not groups:
        out.append("  none")
    for (cls, reason), group in sorted(groups.items()):
        dirs = Counter(str(Path(f["path"]).parent) for f in group)
        top = ", ".join(f"{d}/ ({n})" for d, n in dirs.most_common(3))
        out.append(f"  {cls:10} {len(group):5d} files  {fmt(sum(f['lines'] for f in group)):>9} lines  {reason}")
        out.append(f"  {'':10} {'':5}        {'':9}        in {top}")
    return "\n".join(out)


def area_of(path, depth=2):
    parts = Path(path).parts
    return "/".join(parts[:depth]) + "/" if len(parts) > depth else "/".join(parts[:-1]) + "/" if len(parts) > 1 else "./"


def map_section(ledger):
    files = ledger["files"]
    findings = ledger["findings"]
    per_area = defaultdict(lambda: {"files": 0, "lines": 0, "findings": 0, "high": 0, "classes": Counter()})
    for f in files:
        area = area_of(f["path"])
        entry = per_area[area]
        entry["files"] += 1
        entry["lines"] += f["lines"]
        entry["classes"][f["treatment"]] += 1
    for f in findings:
        entry = per_area[area_of(f["path"])]
        entry["findings"] += 1
        entry["high"] += f["severity"] == "HIGH"
    most = max((e["findings"] for e in per_area.values()), default=0)
    unit = max(1, -(-most // 20))
    out = [f"MAP                                                   scale: one # = {unit} findings"]
    out.append(f"  {'area':38} {'files':>6} {'lines':>9}  {'findings':20}  note")
    for area in sorted(per_area):
        e = per_area[area]
        note = []
        if e["high"]:
            note.append(f"{e['high']} HIGH")
        if e["classes"]["boundary"] == e["files"]:
            note.append("boundary only")
        elif e["classes"]["listed"] == e["files"]:
            note.append("listed only")
        out.append(f"  {area:38} {e['files']:6d} {fmt(e['lines']):>9}  {bar(e['findings'], unit, 16):16} {e['findings']:3d}  {', '.join(note)}")
    return "\n".join(out)


def heat_section(ledger, properties):
    findings = ledger["findings"]
    areas = Counter(area_of(f["path"]) for f in findings)
    top = [a for a, _ in areas.most_common(7)]
    rest = sorted(set(areas) - set(top))
    columns = top + (["other"] if rest else [])
    cells = defaultdict(Counter)
    for f in findings:
        area = area_of(f["path"])
        cells[f["property"]][area if area in top else "other"] += 1
    glyph = lambda n: "." if n == 0 else ":" if n <= 2 else "+" if n <= 5 else "#"
    out = ["HEAT GRID  findings per property and area   . = 0   : = 1-2   + = 3-5   # = 6 or more"]
    if not findings:
        return out[0] + "\n  no findings"
    width = 52
    header = "  " + " " * (width + 4) + " ".join(f"{i + 1:>3}" for i in range(len(columns)))
    out.append(header)
    for index, prop in enumerate(properties, 1):
        row = " ".join(f"{glyph(cells[prop][c]):>3}" for c in columns)
        out.append(f"  {index:2d} {prop[:width]:{width}} {row}   {sum(cells[prop].values()):3d}")
    out.append("  columns:")
    for index, column in enumerate(columns, 1):
        label = column if column != "other" else f"other ({len(rest)} areas)"
        out.append(f"    {index:2d} {label}")
    return "\n".join(out)


def property_ledger(ledger, properties, narrative):
    findings = ledger["findings"]
    na = narrative.get("properties_not_applicable", {})
    checks = narrative.get("property_checks", {})
    out = ["PROPERTY LEDGER                                       scale: one # = 1 finding"]
    out.append(f"  {'#':>2} {'property':52} {'HIGH':>4} {'MED':>4} {'LOW':>4}  status")
    for index, prop in enumerate(properties, 1):
        group = [f for f in findings if f["property"] == prop]
        counts = Counter(f["severity"] for f in group)
        if prop in na:
            status = "n/a, because:"
        elif group:
            status = bar(len(group), 1, 24)
        elif checks.get(prop):
            status = "clean, checked by:"
        else:
            status = "UNVERIFIED: no property_checks entry"
        out.append(f"  {index:2d} {prop[:52]:52} {counts['HIGH']:4d} {counts['MED']:4d} {counts['LOW']:4d}  {status}")
        if status.startswith("clean") or prop in na:
            out.append(field("", checks.get(prop) or na.get(prop), gutter=8, label_width=0).replace("         ", "        ", 1))
    out.append(f"  {'total':55} {sum(f['severity'] == 'HIGH' for f in findings):4d}"
               f" {sum(f['severity'] == 'MED' for f in findings):4d} {sum(f['severity'] == 'LOW' for f in findings):4d}")
    return "\n".join(out)


def reach_section(trials):
    out = ["SEARCH REACH   [x] reached (path in audit.json)  [ ] not reached  [-] n/a  [?] path missing"]
    if not trials:
        return out[0] + "\n  no concepts recorded in vocabulary.json"
    out.append(f"  {'concept':24} {'spellings':30} owner wire  cntr  test  absn  {'hits':>6}")
    keys = ("owner", "wiring", "contract", "tests", "absence")
    totals = Counter()
    for t in trials:
        marks = "  ".join(f"[{t['reach'][k]['mark']}]" for k in keys)
        for k in keys:
            if t["reach"][k]["mark"] in ("x", " "):
                totals[k + "_n"] += 1
                totals[k] += t["reach"][k]["mark"] == "x"
        out.append(f"  {t['concept'][:24]:24} {', '.join(t['spellings'])[:30]:30} {marks}  {fmt(t['hits']):>6}")
    out.append("  reached: " + "  ".join(f"{k} {totals[k]}/{totals[k + '_n']}" for k in keys if totals[k + "_n"]))
    out.append("  hits = git grep -nw count of every spelling across inventoried files")
    return "\n".join(out)


def card(finding, packet_of):
    f = finding
    head = f"{f['id']}  {f['severity']:4}  {f['property']}"
    out = [head + (f"   packet {packet_of[f['id']]}" if f["id"] in packet_of else ""), "-" * len(head)]
    out.append(f"  where     {f['path']}:{f['line']}")
    for line in str(f["evidence"]).splitlines():
        out.append(f"    | {ascii_safe(line.rstrip())}")
    out.append(field("why", f["observation"]))
    for search in f.get("searches", []):
        out.append(f"  search    \"{search.get('term', '')}\" -> {search.get('note', '')}")
    blast = f.get("blast")
    if blast:
        by_class = ", ".join(f"{k} {v}" for k, v in sorted(blast["by_class"].items()))
        out.append(f"  blast     `{blast['symbol']}`: {blast['hits']} hits in {blast['files']} files ({by_class or 'none'})")
        for hit in blast["paths"][:6]:
            out.append(f"              {hit}")
        if len(blast["paths"]) > 6:
            out.append(f"              +{len(blast['paths']) - 6} more in audit.json")
        if "new_symbol" in blast:
            out.append(f"  new name  `{blast['new_symbol']}`: {blast['new_symbol_hits']} existing hits"
                       + (" (free)" if blast["new_symbol_hits"] == 0 else " (collision, choose another)"))
    if f.get("recipe"):
        for index, step in enumerate(f["recipe"], 1):
            out.append(field("recipe" if index == 1 else "", f"{index}. {step}"))
    if f.get("decision"):
        out.append(field("decision", f["decision"].get("question", "")))
        for option in f["decision"].get("options", []):
            out.append(field("", f"- {option}"))
    for index, check in enumerate(f.get("accept", [])):
        argv = " ".join(check["argv"])
        out.append(f"  {'accept' if index == 0 else '      '}    {argv:48} -> {check['expect']}")
    return "\n".join(ascii_safe(line) for line in out)


def one_liner(finding, packet_of):
    f = finding
    action = f"recipe: {f['recipe'][0]}" if f.get("recipe") else f"decision: {f['decision'].get('question', '')}"
    accept = f.get("accept") or []
    tail = f"; accept: {' '.join(accept[0]['argv'])} -> {accept[0]['expect']}" if accept else ""
    first = f"{f['id']}  {f['severity']:4} {f['property'][:40]:40} {f['path']}:{f['line']}" + (f"  {packet_of[f['id']]}" if f["id"] in packet_of else "")
    return ascii_safe(first) + "\n" + field("", f"{action}{tail}", gutter=7, label_width=0).replace("        ", "       ", 1)


def packets_section(ledger):
    packets = ledger.get("packets", [])
    out = ["WORK PACKETS  in dependency order; a packet is done when every accept line holds"]
    if not packets:
        return out[0] + "\n  none recorded in packets.json"
    ids = {f["id"]: f for f in ledger["findings"]}
    for packet in packets:
        sev = Counter(ids[fid]["severity"] for fid in packet["findings"] if fid in ids)
        out.append("")
        out.append(f"  {packet['id']}  {packet['title'][:56]:56} {len(packet['findings']):3d} findings"
                   f"  files {len(packet['files']):3d}  tests {len(packet['tests']):3d}")
        out.append(f"        {' '.join(packet['findings'])}  (HIGH {sev['HIGH']}, MED {sev['MED']}, LOW {sev['LOW']})")
        if packet.get("after"):
            out.append(f"        after: {', '.join(packet['after'])}")
        if packet.get("note"):
            out.append(field("", packet["note"], gutter=8, label_width=0).replace("         ", "        ", 1))
        for index, check in enumerate(packet.get("accept", [])):
            out.append(f"        {'accept:' if index == 0 else '       '} {' '.join(check['argv']):44} -> {check['expect']}")
    if ledger.get("unassigned_findings"):
        out.append("")
        out.append(f"  not in any packet: {' '.join(ledger['unassigned_findings'])}")
    return "\n".join(ascii_safe(line) for line in out)


def appendix(ledger):
    out = ["LEDGER"]
    out.append("  shards")
    for s in ledger["shards"]:
        out.append(f"    {s['id']:6} {s['status']:10} {len(s['files']):4d} files  {fmt(s['lines']):>8} lines" + (f"  parent {s['parent']}" if s["parent"] else ""))
    uncovered = [f for f in ledger["files"] if f["status"] in ("uncovered", "pending")]
    out.append(f"  uncovered or pending files: {len(uncovered)}")
    for f in uncovered:
        out.append(f"    {f['path']}  ({f['status']}: {f['reason'] or 'no reason recorded'})")
    out.append(f"  dropped findings: {len(ledger['dropped'])}")
    for d in ledger["dropped"]:
        out.append(f"    {d['shard']}: {d['reason']}")
    all_problems = ledger["problems"] + ledger.get("measure_problems", [])
    out.append(f"  problems: {len(all_problems)}")
    for p in all_problems:
        out.append(f"    {p}")
    out.append(f"  recovered by re-dispatch: {len(ledger.get('recovered', []))}")
    for r in ledger.get("recovered", []):
        out.append(f"    {r}")
    out.append(f"  git status changes during the audit: {len(ledger['git_status_delta'])}")
    for line in ledger["git_status_delta"]:
        out.append(f"    {line}")
    return "\n".join(ascii_safe(line) for line in out)


def titled(prefix, section):
    title, _, rest = section.partition("\n")
    return prefix + title, rest


def cmd_render(args):
    work = Path(args.work)
    inventory = load(work / "inventory.json")
    ledger = load(work / "ledger.json")
    narrative = load(work / "narrative.json")
    properties = inventory["properties"]
    packet_of = {fid: p["id"] for p in ledger.get("packets", []) for fid in p["findings"]}
    dirty = f"dirty ({len(inventory['dirty'])} entries)" if inventory["dirty"] else "clean"
    head = [
        "GREPPABILITY AUDIT",
        "==================",
        f"Repository : {Path(inventory['repo']).name}  {inventory['origin'] or inventory['repo']}",
        f"Revision   : {inventory['head'][:12]}  {inventory['branch']}  {dirty}",
        f"Scope      : {', '.join(inventory['scope']) if inventory['scope'] else 'whole repository'}",
        f"Rubric     : greppable, {len(properties)} properties",
        "Method     : " + wrap(narrative["method"], REPORT_WIDTH - 13, "             ").lstrip(),
        "Provenance : every count is a row in audit.json; bars and glyphs carry their scale on the same line",
    ]
    uncovered = sum(f["status"] == "uncovered" for f in ledger["files"])
    pending = sum(f["status"] == "pending" for f in ledger["files"])
    complete = uncovered == 0 and pending == 0
    head.insert(6, "Coverage   : complete, every hand-written file read in full" if complete else
                f"Coverage   : INCOMPLETE, {uncovered} uncovered and {pending} pending files (see 10. LEDGER); not a whole-repository audit")
    findings = ledger["findings"]
    high = [f for f in findings if f["severity"] == "HIGH"]
    others = [f for f in findings if f["severity"] != "HIGH"]
    body = []
    for f in high:
        body.append(card(f, packet_of))
        body.append("")
    if others:
        body.append("MED and LOW")
        body.extend(one_liner(f, packet_of) for f in others)
    handoff = wrap(
        "Fix in packet order. For each packet: apply every recipe, resolve every decision with the user before "
        "touching it, run the packet's accept lines, then each finding's accept lines. A packet is done when "
        "all accept lines hold and git status shows only files it lists. Full detail with the same IDs is in "
        f"{Path(args.json).name} beside this report (findings[].blast.paths, findings[].recipe, packets[].accept).")
    sections = [
        ("1. VERDICT", wrap(narrative["verdict"])),
        titled("2. ", map_section(ledger)),
        titled("3. ", coverage_table(inventory, ledger) + "\n\n" + exclusion_table(ledger["files"])),
        titled("4. ", heat_section(ledger, properties)),
        titled("5. ", property_ledger(ledger, properties, narrative)),
        titled("6. ", reach_section(ledger.get("trials", []))),
        (f"7. FINDINGS  {len(findings)} accepted, {len(ledger['dropped'])} dropped; HIGH as cards, MED and LOW as one-liners",
         "\n".join(body).rstrip()),
        titled("8. ", packets_section(ledger)),
        ("9. HANDOFF", handoff),
        titled("10. ", appendix(ledger)),
    ]
    parts = ["\n".join(head)] + [f"{title}\n{'-' * len(title)}\n{text}" for title, text in sections]
    report = "\n\n".join(parts) + "\n"
    report = ascii_safe(report)
    Path(args.out).write_text(report)
    audit = {
        "repository": {k: inventory[k] for k in ("repo", "origin", "head", "branch", "dirty", "scope")},
        "rubric": {"path": inventory["rubric"], "properties": properties},
        "narrative": narrative,
        "coverage": {cls: Counter(f["status"] for f in ledger["files"] if f["class"] == cls) for cls in CLASS_ORDER},
        "files": ledger["files"],
        "findings": findings,
        "dropped": ledger["dropped"],
        "trials": ledger.get("trials", []),
        "packets": ledger.get("packets", []),
        "unassigned_findings": ledger.get("unassigned_findings", []),
        "shards": ledger["shards"],
        "problems": ledger["problems"] + ledger.get("measure_problems", []),
        "recovered": ledger.get("recovered", []),
        "git_status_delta": ledger["git_status_delta"],
    }
    dump(args.json, audit)
    print(progress_line(ledger))
    if not complete:
        print(f"incomplete: {uncovered} uncovered and {pending} pending files; do not deliver this as a whole-repository audit")
    print(f"report: {args.out} ({report.count(chr(10))} lines, 7-bit ASCII)  data: {args.json}")


# --- main ----------------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("inventory", help="enumerate, classify, and shard every file in the repository")
    p.add_argument("--repo", default=".")
    p.add_argument("--work", required=True, help="artifact directory outside the repository")
    p.add_argument("--scope", action="append", default=[], help="restrict to a repository-relative path (repeatable)")
    p.add_argument("--shard-lines", type=int, default=DEFAULT_SHARD_LINES)
    p.add_argument("--override", action="append", default=[], metavar="PREFIX=CLASS",
                   help="force a class for everything under PREFIX (repeatable)")
    p.add_argument("--rubric", help="path to the greppable SKILL.md (default: sibling skill)")
    p.set_defaults(func=cmd_inventory)

    p = sub.add_parser("shard-prompt", help="print the complete prompt for one shard")
    p.add_argument("--work", required=True)
    p.add_argument("--shard", required=True)
    p.set_defaults(func=cmd_shard_prompt)

    p = sub.add_parser("verify", help="reconcile shard artifacts against assignments and check evidence")
    p.add_argument("--work", required=True)
    p.set_defaults(func=cmd_verify)

    p = sub.add_parser("measure", help="measure blast radii, search trials, and packets")
    p.add_argument("--work", required=True)
    p.set_defaults(func=cmd_measure)

    p = sub.add_parser("render", help="write the ASCII report and the same-ID JSON")
    p.add_argument("--work", required=True)
    p.add_argument("--out", required=True, help="audit.txt path")
    p.add_argument("--json", required=True, help="audit.json path")
    p.set_defaults(func=cmd_render)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
