"""Behavioral tests for audit.py on a throwaway git repository. Run: python3 -m unittest test_audit"""

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "audit.py"
RUBRIC = Path(__file__).resolve().parent.parent.parent / "greppable" / "SKILL.md"

FILES = {
    "src/billing/invoice.ts": "export function process(input) {\n  return normalize(input);\n}\n" + "x\n" * 30,
    "src/shared/utils.ts": "export * from './x';\nexport function process(a) { return a; }\n",
    "tests/billing/invoice.test.ts": "import { process } from '../../src/billing/invoice';\ntest('process', () => {});\n",
    "migrations/001_init.sql": "create table organization (id text);\n",
    "scripts/release.sh": "#!/bin/sh\necho release\n",
    "README.md": "# Demo\nThe organization concept lives in src/billing.\n",
    "package.json": "{\"name\": \"demo\"}\n",
    "generated/api.ts": "// @generated by protoc, DO NOT EDIT\nexport const x = 1;\n",
    "vendor/lib.js": "module.exports = 1;\n",
    "gen/domain.ts": "export function loadGenome() {}\n",
    "tests/fixtures/sample.json": "{}\n",
    "package-lock.json": "{}\n",
    ".github/CODEOWNERS": "* @owner\n",
    "CHANGELOG.md": "# Changelog\n",
    "LICENSE": "MIT\n",
}


def run(*args, cwd=None):
    result = subprocess.run([sys.executable, str(SCRIPT), *args], capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        raise AssertionError(f"{' '.join(args)}\n{result.stdout}\n{result.stderr}")
    return result.stdout


class AuditFlow(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.repo = root / "repo"
        self.work = root / "work"
        for rel, text in FILES.items():
            path = self.repo / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        (self.repo / "logo.png").write_bytes(b"\x89PNG\x00\x00")
        git = lambda *a: subprocess.run(["git", "-C", str(self.repo), *a], check=True, capture_output=True)
        git("init", "-q")
        git("-c", "user.email=t@t", "-c", "user.name=t", "add", ".")
        git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init")
        (self.repo / "untracked.ts").write_text("export const y = 2;\n")

    def tearDown(self):
        self.tmp.cleanup()

    def inventory(self, *extra):
        run("inventory", "--repo", str(self.repo), "--work", str(self.work), "--rubric", str(RUBRIC), "--shard-lines", "20", *extra)
        return json.loads((self.work / "inventory.json").read_text())

    def test_inventory_classifies_and_shards_every_file(self):
        inventory = self.inventory()
        by_path = {f["path"]: f for f in inventory["files"]}
        expected = {
            "src/billing/invoice.ts": "source", "tests/billing/invoice.test.ts": "test", "migrations/001_init.sql": "schema",
            "scripts/release.sh": "script", "README.md": "docs", "package.json": "config", "generated/api.ts": "generated",
            "vendor/lib.js": "vendored", "gen/domain.ts": "generated", "tests/fixtures/sample.json": "data",
            "package-lock.json": "data", "logo.png": "binary", "untracked.ts": "source",
            ".github/CODEOWNERS": "config", "CHANGELOG.md": "docs", "LICENSE": "data",
        }
        for path, cls in expected.items():
            self.assertEqual(by_path[path]["class"], cls, path)
        self.assertEqual(len(inventory["properties"]), 19)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        assigned = sorted(p for s in shards for p in s["files"])
        self.assertEqual(assigned, sorted(f["path"] for f in inventory["files"] if f["treatment"] == "read"))
        self.assertGreater(len(shards), 1)

    def test_override_rescues_misclassified_directory(self):
        inventory = self.inventory("--override", "gen=source")
        by_path = {f["path"]: f for f in inventory["files"]}
        self.assertEqual(by_path["gen/domain.ts"]["treatment"], "read")

    def test_work_dir_inside_repo_is_refused(self):
        result = subprocess.run([sys.executable, str(SCRIPT), "inventory", "--repo", str(self.repo), "--work",
                                 str(self.repo / "work"), "--rubric", str(RUBRIC)], capture_output=True, text=True)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse((self.repo / "work").exists())

    def artifact(self, shard, read, skipped, findings, declare=True):
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        return {"shard": shard["id"], "properties_checked": properties if declare else properties[:-1],
                "files_read": [{"path": p, "lines": 1} for p in read],
                "files_skipped": [{"path": p, "reason": "ran out of budget"} for p in skipped],
                "findings": findings, "cross_shard_leads": [], "vocabulary_additions": []}

    def test_shard_without_full_property_declaration_reads_nothing(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, shard["files"], [], [], declare=False)))
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertIn("properties not declared checked", out)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], shard["files"])
        # Once the child covers every file the parent's message is recovered evidence, not a problem.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, child["files"], [], [])))
        out = run("verify", "--work", str(self.work))
        self.assertIn("uncovered 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(ledger["problems"], [])
        self.assertEqual(len(ledger["recovered"]), 1)

    def test_coverage_is_recomputed_from_present_artifacts(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        artifact = self.work / "shards" / f"{shard['id']}.json"
        artifact.write_text(json.dumps(self.artifact(shard, shard["files"], [], [])))
        self.assertIn("(100%)", run("verify", "--work", str(self.work)))
        artifact.unlink()
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertEqual(json.loads((self.work / "shards.json").read_text())["shards"][0]["status"], "pending")
        artifact.write_text("{not json")
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertIn("not valid JSON", out)

    def test_full_flow_reconciles_verifies_measures_and_renders(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        prompt = run("shard-prompt", "--work", str(self.work), "--shard", shard["id"])
        self.assertIn("## Rubric", prompt)
        self.assertIn("src/billing/invoice.ts", prompt)
        good = {
            "property": "Use distinctive domain names", "severity": "HIGH", "path": "src/billing/invoice.ts", "line": 1,
            "evidence": "export function process(input) {", "observation": "generic verb without its object",
            "symbol": "process", "new_symbol": "processInvoice", "recipe": ["rename process -> processInvoice"],
        }
        fabricated = {**good, "path": "src/shared/utils.ts", "line": 1, "evidence": "this line does not exist"}
        no_fix = {**good, "path": "src/shared/utils.ts", "line": 2, "evidence": "export function process(a)", "recipe": None}
        both = {**good, "line": 2, "evidence": "return normalize(input);", "decision": {"question": "q", "options": ["a"]}}
        no_check = {**good, "line": 3, "evidence": "}", "symbol": None}
        read = [p for p in shard["files"] if p != "README.md"]
        artifact = self.artifact(shard, read, ["README.md"], [good, fabricated, no_fix, both, no_check])
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(artifact))
        out = run("verify", "--work", str(self.work))
        self.assertIn("RE-DISPATCH", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual([f["id"] for f in ledger["findings"]], ["F-001"])
        self.assertEqual(len(ledger["dropped"]), 4)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], ["README.md"])
        # Second miss on the re-dispatched shard turns the file into uncovered rather than looping.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, [], ["README.md"], [])))
        (self.work / "shards" / "main.json").write_text(json.dumps({"shard": "main", "files_read": [], "files_skipped": [], "findings": [
            {"property": "Make paths and exports say where code lives", "severity": "MED", "path": "src/shared/utils.ts", "line": 1,
             "evidence": "export * from './x';", "observation": "star re-export hides names",
             "decision": {"question": "which module owns utils", "options": ["billing", "delete"]},
             "accept": [{"argv": ["git", "grep", "-n", "export \\*", "--", "src"], "expect": "0 hits"}]},
            dict(good)]}))
        out = run("verify", "--work", str(self.work))
        self.assertIn("uncovered 1", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(sorted(f["shard"] for f in ledger["findings"]), sorted(["main", shard["id"]]))
        # The main-pass copy of `good` is an exact duplicate and must not get a second ID.
        self.assertEqual(len(ledger["findings"]), 2)
        self.assertTrue(any(d["reason"].startswith("duplicate of") for d in ledger["dropped"]))
        self.assertEqual(next(f for f in ledger["files"] if f["path"] == "README.md")["status"], "uncovered")
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [
            {"concept": "organization", "spellings": ["organization"],
             "reach": {"owner": "migrations/001_init.sql", "wiring": None, "contract": "n/a", "tests": None, "absence": "missing/file.ts"}}]}))
        ids = [f["id"] for f in ledger["findings"]]
        packets = {"packets": [
            {"id": "P-02", "title": "Rename process", "findings": ids[:1], "after": ["P-01"], "accept": []},
            {"id": "P-01", "title": "Own utils", "findings": ids[1:], "after": [], "accept": [{"argv": ["git", "grep", "-n", "export \\*"], "expect": "0 hits"}]}]}
        (self.work / "packets.json").write_text(json.dumps(packets))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        clean = [p for p in properties if p not in ("Use distinctive domain names", "Make paths and exports say where code lives")]
        narrative = {"verdict": "Names are generic.", "method": "1 shard, sequential.",
                     "property_checks": {p: "checked in every file read; no violation" for p in clean[1:]}}
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        out = run("measure", "--work", str(self.work))
        self.assertIn("2 packets", out)
        self.assertIn("packet P-02: accept must be a non-empty list", out)
        self.assertIn("path not in inventory: missing/file.ts", out)
        self.assertIn(f"no property_checks evidence: {clean[0]!r}", out)
        # Fixing the artifacts and rerunning measure clears its problems instead of accumulating them.
        packets["packets"][0]["accept"] = [{"argv": ["git", "grep", "-nw", "--", "processInvoice"], "expect": "definition and calls"}]
        (self.work / "packets.json").write_text(json.dumps(packets))
        narrative["property_checks"][clean[0]] = "git grep -n ' as ' -- '*.ts' = 0"
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        vocabulary = json.loads((self.work / "vocabulary.json").read_text())
        vocabulary["concepts"][0]["reach"]["absence"] = "n/a"
        (self.work / "vocabulary.json").write_text(json.dumps(vocabulary))
        out = run("measure", "--work", str(self.work))
        self.assertIn("problems 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        blast = next(f for f in ledger["findings"] if f["id"] == "F-001")["blast"]
        self.assertEqual(blast["files"], 3)
        self.assertEqual(blast["new_symbol_hits"], 0)
        self.assertEqual([p["id"] for p in ledger["packets"]], ["P-01", "P-02"])
        self.assertEqual(ledger["trials"][0]["reach"]["absence"]["mark"], "-")
        self.assertEqual(ledger["measure_problems"], [])
        report = self.work / "audit.txt"
        out = run("render", "--work", str(self.work), "--out", str(report), "--json", str(self.work / "audit.json"))
        text = report.read_text()
        text.encode("ascii")
        for section in ("1. VERDICT", "2. MAP", "3. COVERAGE", "4. HEAT GRID", "5. PROPERTY LEDGER", "6. SEARCH REACH",
                        "7. FINDINGS", "8. WORK PACKETS", "9. HANDOFF", "10. LEDGER"):
            self.assertIn(section, text)
        self.assertIn("F-001  HIGH", text)
        self.assertIn("README.md  (uncovered", text)
        self.assertIn("scale: one # =", text)
        self.assertIn("Coverage   : INCOMPLETE, 1 uncovered", text)
        self.assertIn("incomplete: 1 uncovered", out)
        self.assertIn("git grep -n ' as ' -- '*.ts' = 0", text)
        self.assertNotIn("UNVERIFIED", text)
        audit = json.loads((self.work / "audit.json").read_text())
        self.assertEqual([f["id"] for f in audit["findings"]], ids)
        self.assertEqual(len(audit["dropped"]), 5)
        self.assertEqual(audit["problems"], [])


if __name__ == "__main__":
    unittest.main()
