"""Behavioral tests for audit.py on a throwaway git repository. Run: python3 -m unittest test_audit"""

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "audit.py"
RUBRIC = Path(__file__).resolve().parent.parent.parent / "greppable" / "SKILL.md"
SPEC = importlib.util.spec_from_file_location("audit_script", SCRIPT)
AUDIT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(AUDIT)

FILES = {
    "src/billing/invoice.ts": "export function process(input) {\n  return normalize(input);\n}\n" + "x\n" * 30,
    "src/shared/utils.ts": "export * from './x';\nexport function process(a) { return a; }\n",
    "tests/billing/invoice.test.ts": "import { process } from '../../src/billing/invoice';\ntest('process', () => {});\n",
    "migrations/001_init.sql": "create table organization (id text);\n",
    "scripts/release.sh": "#!/bin/sh\necho release\n",
    "README.md": "# Demo\nThe organization concept lives in src/billing.\n",
    "package.json": "{\"name\": \"demo\"}\n",
    "generated/api.ts": "// @generated by protoc, DO NOT EDIT\nexport const x = 1;\n",
    "vendor/lib.js": "module.exports = 1;\n",
    "gen/domain.ts": "export function loadGenome() {}\n",
    "tests/fixtures/sample.json": "{}\n",
    "package-lock.json": "{}\n",
    ".github/CODEOWNERS": "* @owner\n",
    "CHANGELOG.md": "# Changelog\n",
    "LICENSE": "MIT\n",
}


def run(*args, cwd=None):
    result = subprocess.run([sys.executable, str(SCRIPT), *args], capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        raise AssertionError(f"{' '.join(args)}\n{result.stdout}\n{result.stderr}")
    return result.stdout


class AuditFlow(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.repo = root / "repo"
        self.work = root / "work"
        for rel, text in FILES.items():
            path = self.repo / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        (self.repo / "logo.png").write_bytes(b"\x89PNG\x00\x00")
        git = lambda *a: subprocess.run(["git", "-C", str(self.repo), *a], check=True, capture_output=True)
        git("init", "-q")
        git("-c", "user.email=t@t", "-c", "user.name=t", "add", ".")
        git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init")
        (self.repo / "untracked.ts").write_text("export const y = 2;\n")

    def tearDown(self):
        self.tmp.cleanup()

    def inventory(self, *extra):
        run("inventory", "--repo", str(self.repo), "--work", str(self.work), "--rubric", str(RUBRIC), "--shard-lines", "20", *extra)
        return json.loads((self.work / "inventory.json").read_text())

    def test_inventory_classifies_and_shards_every_file(self):
        inventory = self.inventory()
        by_path = {f["path"]: f for f in inventory["files"]}
        expected = {
            "src/billing/invoice.ts": "source", "tests/billing/invoice.test.ts": "test", "migrations/001_init.sql": "schema",
            "scripts/release.sh": "script", "README.md": "docs", "package.json": "config", "generated/api.ts": "generated",
            "vendor/lib.js": "vendored", "gen/domain.ts": "generated", "tests/fixtures/sample.json": "data",
            "package-lock.json": "data", "logo.png": "binary", "untracked.ts": "source",
            ".github/CODEOWNERS": "config", "CHANGELOG.md": "docs", "LICENSE": "data",
        }
        for path, cls in expected.items():
            self.assertEqual(by_path[path]["class"], cls, path)
        self.assertEqual(len(inventory["properties"]), 19)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        assigned = sorted(p for s in shards for p in s["files"])
        self.assertEqual(assigned, sorted(f["path"] for f in inventory["files"] if f["treatment"] == "read"))
        self.assertGreater(len(shards), 1)

    def test_override_rescues_misclassified_directory(self):
        inventory = self.inventory("--override", "gen=source")
        by_path = {f["path"]: f for f in inventory["files"]}
        self.assertEqual(by_path["gen/domain.ts"]["treatment"], "read")

    def test_work_dir_inside_repo_is_refused(self):
        result = subprocess.run([sys.executable, str(SCRIPT), "inventory", "--repo", str(self.repo), "--work",
                                 str(self.repo / "work"), "--rubric", str(RUBRIC)], capture_output=True, text=True)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse((self.repo / "work").exists())

    def artifact(self, shard, read, skipped, findings, declare=True):
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        return {"shard": shard["id"], "properties_checked": properties if declare else properties[:-1],
                "files_read": [{"path": p, "lines": 1} for p in read],
                "files_skipped": [{"path": p, "reason": "ran out of budget"} for p in skipped],
                "findings": findings, "cross_shard_leads": [], "vocabulary_additions": []}

    def test_shard_without_full_property_declaration_reads_nothing(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, shard["files"], [], [], declare=False)))
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertIn("properties not declared checked", out)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], shard["files"])
        # Once the child covers every file the parent's message is recovered evidence, not a problem.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, child["files"], [], [])))
        out = run("verify", "--work", str(self.work))
        self.assertIn("uncovered 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(ledger["problems"], [])
        self.assertEqual(len(ledger["recovered"]), 1)

    def test_coverage_is_recomputed_from_present_artifacts(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        artifact = self.work / "shards" / f"{shard['id']}.json"
        artifact.write_text(json.dumps(self.artifact(shard, shard["files"], [], [])))
        self.assertIn("(100%)", run("verify", "--work", str(self.work)))
        artifact.unlink()
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertEqual(json.loads((self.work / "shards.json").read_text())["shards"][0]["status"], "pending")
        artifact.write_text("{not json")
        out = run("verify", "--work", str(self.work))
        self.assertIn("read 0/", out)
        self.assertIn("not valid JSON", out)

    def test_full_flow_reconciles_verifies_measures_and_renders(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        prompt = run("shard-prompt", "--work", str(self.work), "--shard", shard["id"])
        self.assertIn("## Rubric", prompt)
        self.assertIn("src/billing/invoice.ts", prompt)
        good = {
            "property": "Use distinctive domain names", "severity": "HIGH", "path": "src/billing/invoice.ts", "line": 1,
            "evidence": "export function process(input) {", "observation": "generic verb without its object",
            "symbol": "process", "new_symbol": "processInvoice", "recipe": ["rename process -> processInvoice"],
        }
        fabricated = {**good, "path": "src/shared/utils.ts", "line": 1, "evidence": "this line does not exist"}
        no_fix = {**good, "path": "src/shared/utils.ts", "line": 2, "evidence": "export function process(a)", "recipe": None}
        both = {**good, "line": 2, "evidence": "return normalize(input);", "decision": {"question": "q", "options": ["a"]}}
        no_check = {**good, "line": 3, "evidence": "}", "symbol": None}
        read = [p for p in shard["files"] if p != "README.md"]
        artifact = self.artifact(shard, read, ["README.md"], [good, fabricated, no_fix, both, no_check])
        artifact["vocabulary_additions"] = [
            {"concept": "invoice", "spellings": ["invoice"], "paths": ["src/billing/invoice.ts:1"]}
        ]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(artifact))
        out = run("verify", "--work", str(self.work))
        self.assertIn("RE-DISPATCH", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual([f["id"] for f in ledger["findings"]], ["F-001"])
        self.assertEqual(len(ledger["dropped"]), 4)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], ["README.md"])
        # Second miss on the re-dispatched shard turns the file into uncovered rather than looping.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, [], ["README.md"], [])))
        (self.work / "shards" / "main.json").write_text(json.dumps({"shard": "main", "files_read": [], "files_skipped": [], "findings": [
            {"property": "Make paths and exports say where code lives", "severity": "MED", "path": "src/shared/utils.ts", "line": 1,
             "evidence": "export * from './x';", "observation": "star re-export hides names",
             "decision": {"question": "which module owns utils", "options": ["billing", "delete"],
                          "recommendation": "Delete the generic re-export so billing owns the symbol."},
             "accept": [{"argv": ["git", "grep", "-n", "export \\*", "--", "src"], "expect": "0 hits"}]},
            dict(good)]}))
        out = run("verify", "--work", str(self.work))
        self.assertIn("uncovered 1", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(sorted(f["shard"] for f in ledger["findings"]), sorted(["main", shard["id"]]))
        # The main-pass copy of `good` is an exact duplicate and must not get a second ID.
        self.assertEqual(len(ledger["findings"]), 2)
        self.assertTrue(any(d["reason"].startswith("duplicate of") for d in ledger["dropped"]))
        self.assertEqual(next(f for f in ledger["files"] if f["path"] == "README.md")["status"], "uncovered")
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [
            {"concept": "organization", "spellings": ["organization"], "documented": "README.md:2",
             "reach": {"owner": "migrations/001_init.sql", "wiring": None, "contract": "n/a", "tests": "n/a", "absence": "missing/file.ts"},
             "findings": []}], "rejected": []}))
        ids = [f["id"] for f in ledger["findings"]]
        packets = {"packets": [
            {"id": "P-02", "title": "Rename process", "findings": ids[:1], "after": ["P-01"], "accept": []},
            {"id": "P-01", "title": "Own utils", "findings": ids[1:], "after": [], "accept": [{"argv": ["git", "grep", "-n", "export \\*"], "expect": "0 hits"}]}]}
        (self.work / "packets.json").write_text(json.dumps(packets))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        clean = [p for p in properties if p not in ("Use distinctive domain names", "Make paths and exports say where code lives")]
        narrative = {"verdict": "Names are generic.", "method": "1 shard | sequential.",
                     "property_checks": {p: "checked in every file read; no violation" for p in clean[1:]},
                     "themes": [
                         {"title": "Give invoice processing a domain name",
                          "explanation": "The main operation is named process, so searches reach unrelated operations. Rename it to processInvoice.",
                          "findings": [ids[0]], "packets": ["P-02"]},
                         {"title": "Import the billing contract directly",
                          "explanation": "A star export hides the owning module, so readers must open it to discover the contract. Remove the generic re-export.",
                          "findings": [ids[1]], "packets": ["P-01"]},
                     ]}
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        out = run("measure", "--work", str(self.work))
        self.assertIn("2 packets", out)
        self.assertIn("packet P-02: accept must be a non-empty list", out)
        self.assertIn("path not in inventory: missing/file.ts", out)
        self.assertIn("unresolved addition invoice", out)
        self.assertIn("misses wiring without an accepted finding", out)
        self.assertIn(f"no property_checks evidence: {clean[0]!r}", out)
        # Fixing the artifacts and rerunning measure clears its problems instead of accumulating them.
        packets["packets"][0]["accept"] = [{"argv": ["git", "grep", "-nw", "--", "processInvoice"], "expect": "definition and calls"}]
        (self.work / "packets.json").write_text(json.dumps(packets))
        narrative["property_checks"][clean[0]] = "git grep -n ' as ' -- '*.ts' = 0"
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        vocabulary = json.loads((self.work / "vocabulary.json").read_text())
        vocabulary["concepts"][0]["reach"]["absence"] = "n/a"
        vocabulary["concepts"][0]["findings"] = [ids[0]]
        vocabulary["concepts"].append({
            "concept": "invoice", "spellings": ["invoice"], "documented": None,
            "reach": {"owner": "src/billing/invoice.ts", "wiring": "n/a", "contract": "n/a",
                      "tests": "tests/billing/invoice.test.ts", "absence": "n/a"},
            "findings": [],
        })
        (self.work / "vocabulary.json").write_text(json.dumps(vocabulary))
        out = run("measure", "--work", str(self.work))
        self.assertIn("problems 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        blast = next(f for f in ledger["findings"] if f["id"] == "F-001")["blast"]
        self.assertEqual(blast["files"], 3)
        self.assertEqual(blast["new_symbol_hits"], 0)
        self.assertEqual([p["id"] for p in ledger["packets"]], ["P-01", "P-02"])
        self.assertEqual(ledger["trials"][0]["reach"]["absence"]["mark"], "-")
        self.assertEqual(ledger["trials"][1]["documented"]["mark"], " ")
        self.assertEqual(ledger["measure_problems"], [])
        report = self.work / "audit.md"
        out = run("render", "--work", str(self.work), "--out", str(report))
        text = report.read_text()
        self.assertTrue(text.startswith("```text\n" + AUDIT.GREP_WORDMARK))
        self.assertIn(AUDIT.GREP_WORDMARK, (SCRIPT.parent.parent / "SKILL.md").read_text())
        self.assertIn("GREPPABILITY AUDIT", text)
        self.assertIn("A read-only audit of how easily coding agents can work in repo.", text)
        for section in ("## 1. Verdict", "## 2. Repository map", "## 3. Coverage", "## 4. Heat grid",
                        "## 5. Rubric scorecard", "## 6. Search reach", "## 7. Findings",
                        "## 8. Work packets", "## 9. Handoff", "## 10. Reconciliation ledger"):
            self.assertIn(section, text)
        self.assertIn("DIMENSION SCORES", text)
        self.assertIn("Names & vocabulary", text)
        for finding_id in ids:
            self.assertIn(f"### {finding_id} -", text)
        self.assertIn("### P-01 -", text)
        self.assertIn("### P-02 -", text)
        self.assertIn("### F-001 - HIGH", text)
        self.assertIn("**HIGH:** A domain search cannot reach the concept's owner or contract.", text)
        self.assertIn("**MED:** Search reaches the owner or contract only after extra reads or context reconstruction.", text)
        self.assertIn("**LOW:** Search succeeds, but inconsistent names or structure still add friction.", text)
        self.assertIn("star re-export hides names", text)
        self.assertIn("proof", text)
        self.assertIn("vocabulary additions: 1", text)
        self.assertIn("README.md  (uncovered", text)
        self.assertIn("scale: one # =", text)
        self.assertIn("**Coverage:** INCOMPLETE: 1 uncovered", text)
        self.assertIn("incomplete: 1 uncovered", out)
        self.assertIn("git grep -n ' as ' -- '*.ts' = 0", text)
        self.assertIn("1 shard \\| sequential.", text)
        self.assertNotIn("UNVERIFIED", text)
        self.assertNotIn("audit.json", text)
        self.assertIn("report:", out)
        self.assertIn("branded UTF-8 header and ASCII visuals", out)
        self.assertNotIn("data:", out)
        in_fence = False
        for line in text.splitlines():
            if line.startswith("```"):
                in_fence = not in_fence
            elif in_fence:
                self.assertLessEqual(len(line), 100, line)
        self.assertFalse(in_fence)
        audit = json.loads((self.work / "audit.json").read_text())
        self.assertEqual([f["id"] for f in audit["findings"]], ids)
        self.assertEqual(len(audit["dropped"]), 5)
        self.assertEqual(audit["problems"], [])
        self.assertIsNone(audit["score"]["value"])
        card = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        self.assertIn("GREPPABILITY AUDIT", card)
        self.assertIn("SCORE  WITHHELD", card)
        self.assertIn("TOP IMPROVEMENTS", card)
        self.assertIn("Give invoice processing a domain name", card)
        self.assertIn("─" * 78, card)
        self.assertTrue(card.rstrip().endswith(f"Detailed audit   {report.resolve()}"))

    def test_measure_rejects_open_or_untrialed_vocabulary(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        artifact = self.artifact(shard, shard["files"], [], [])
        artifact["vocabulary_additions"] = [
            {"concept": "invoice", "spellings": ["invoice", "bill"], "paths": ["src/billing/invoice.ts"]}
        ]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(artifact))
        run("verify", "--work", str(self.work))
        (self.work / "vocabulary.json").write_text(json.dumps({
            "concepts": [{
                "concept": "organization", "spellings": ["organization"], "documented": "README.md:2",
                "reach": {"owner": "src/shared/utils.ts:1"}, "findings": [],
            }],
            "rejected": [],
        }))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        narrative = {
            "verdict": "No findings.", "method": "1 shard, sequential.", "themes": [],
            "property_checks": {property_name: "checked" for property_name in properties},
        }
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        (self.work / "packets.json").write_text(json.dumps({"packets": []}))
        out = run("measure", "--work", str(self.work))
        self.assertIn("unresolved addition invoice: invoice, bill", out)
        self.assertIn("not trialed: missing reach wiring, contract, tests, absence", out)
        self.assertIn("proof contains none of its spellings", out)
        inventory = json.loads((self.work / "inventory.json").read_text())
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertIsNone(AUDIT.audit_score(inventory, ledger, narrative)["value"])

        vocabulary = json.loads((self.work / "vocabulary.json").read_text())
        vocabulary["concepts"][0]["reach"] = {
            "owner": "migrations/001_init.sql", "wiring": "n/a", "contract": "n/a",
            "tests": "n/a", "absence": "n/a",
        }
        vocabulary["rejected"] = [{
            "concept": "invoice", "spellings": ["invoice", "bill"],
            "reason": "The shard reported a feature word already covered by the billing boundary.",
        }]
        (self.work / "vocabulary.json").write_text(json.dumps(vocabulary))
        out = run("measure", "--work", str(self.work))
        self.assertIn("problems 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(ledger["vocabulary_rejected"][0]["concept"], "invoice")
        self.assertEqual(AUDIT.audit_score(inventory, ledger, narrative)["value"], 100)

    def test_vocabulary_search_finds_compound_identifiers(self):
        path = self.repo / "src" / "organization-runtime.ts"
        path.write_text("export const organizationId = 'o1';\nexport class OrganizationRepository {}\n")
        inventory = self.inventory()
        by_path = {file["path"]: file for file in inventory["files"]}
        hits = AUDIT.grep_hits(self.repo, "organization", by_path, whole_word=False)
        self.assertIn("src/organization-runtime.ts:1", hits)
        self.assertIn("src/organization-runtime.ts:2", hits)

    def test_score_uses_worst_severity_per_property(self):
        properties = AUDIT.rubric_headings(RUBRIC)
        affected = {properties[0], properties[4], properties[11]}
        inventory = {"properties": properties}
        findings = [
            {"property": properties[0], "severity": "MED"},
            {"property": properties[0], "severity": "LOW"},
            {"property": properties[4], "severity": "MED"},
            {"property": properties[11], "severity": "MED"},
        ]
        ledger = {"findings": findings, "files": [], "problems": [], "measure_problems": [],
                  "unassigned_findings": []}
        narrative = {"property_checks": {prop: "checked" for prop in properties if prop not in affected},
                     "properties_not_applicable": {}}
        score = AUDIT.audit_score(inventory, ledger, narrative)
        self.assertEqual(score["value"], 92)
        self.assertEqual(score["clean"], 16)
        self.assertEqual(score["affected"], 3)
        self.assertEqual([dimension["value"] for dimension in score["dimensions"]], [88, 83, 100, 100, 100])
        mapped = {prop for _, dimension_properties in AUDIT.DIMENSIONS for prop in dimension_properties}
        self.assertEqual(set(properties), mapped)

    def test_card_renders_complete_score_and_absolute_report_path(self):
        properties = AUDIT.rubric_headings(RUBRIC)
        affected = {properties[0], properties[4], properties[11]}
        findings = [
            {"id": "F-001", "property": properties[0], "severity": "MED", "path": "src/config.rs", "line": 10},
            {"id": "F-002", "property": properties[4], "severity": "MED", "path": "src/overlay.rs", "line": 20},
            {"id": "F-003", "property": properties[11], "severity": "MED", "path": "src/tui.rs", "line": 30},
            {"id": "F-004", "property": properties[0], "severity": "LOW", "path": "src/tui.rs", "line": 40},
        ]
        files = [{"path": f"src/file-{index}.rs", "treatment": "read", "status": "read-in-full"} for index in range(34)]
        ledger = {"findings": findings, "files": files, "problems": [], "measure_problems": [],
                  "unassigned_findings": []}
        narrative = {
            "verdict": "Search reaches every owner, but three properties add avoidable reconstruction.",
            "property_checks": {prop: "checked" for prop in properties if prop not in affected},
            "properties_not_applicable": {},
            "themes": [{"title": "Give owners domain-specific names",
                        "explanation": "Several owner names need module context, so a reader opens extra files before finding the right owner. Split the TUI by responsibility.",
                        "findings": [f["id"] for f in findings], "packets": ["P-01"]}],
        }
        score = AUDIT.audit_score({"properties": properties}, ledger, narrative)
        audit = {
            "repository": {"repo": "/repos/mdmanager", "head": "de72aec815b61234", "branch": "main", "dirty": []},
            "narrative": narrative, "score": score, "findings": findings,
            "packets": [{"id": "P-01", "title": "Give owners domain-specific names", "findings": [f["id"] for f in findings]}],
            "trials": [], "files": files, "dropped": [], "problems": [],
        }
        (self.work / "audit.json").parent.mkdir(parents=True, exist_ok=True)
        (self.work / "audit.json").write_text(json.dumps(audit))
        report = self.work / "audit.md"
        card = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        self.assertIn("SCORE  92   ●●●●●●●●●●●●●●●●○○○", card)
        self.assertIn("16 of 19 properties clean", card)
        self.assertIn("No high-risk findings · 4 improvements recommended", card)
        self.assertIn("DIMENSION SCORES", card)
        self.assertIn("Names & vocabulary           88   ●●●●●●●●●○", card)
        self.assertIn("Ownership & layout           83   ●●●●●●●●○○", card)
        self.assertIn("Contracts & boundaries      100   ●●●●●●●●●●", card)
        self.assertIn("Give owners domain-specific names", card)
        self.assertTrue(card.rstrip().endswith(f"Detailed audit   {report.resolve()}"))


if __name__ == "__main__":
    unittest.main()
