"""Behavioral tests for audit.py on a throwaway git repository. Run: python3 -m unittest test_audit"""

import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import unittest
from collections import Counter
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "audit.py"
RUBRIC = Path(__file__).resolve().parent.parent.parent / "greppable" / "SKILL.md"
SPEC = importlib.util.spec_from_file_location("audit_script", SCRIPT)
AUDIT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(AUDIT)

FILES = {
    "src/billing/invoice.ts": "export function process(input) {\n  return normalize(input);\n}\n" + "x\n" * 30,
    "src/shared/utils.ts": "export * from './x';\nexport function process(a) { return a; }\n",
    "tests/billing/invoice.test.ts": "import { process } from '../../src/billing/invoice';\ntest('process', () => {});\n",
    "migrations/001_init.sql": "create table organization (id text);\n",
    "scripts/release.sh": "#!/bin/sh\necho release\n",
    "README.md": "# Demo\nThe organization concept lives in src/billing.\n",
    "package.json": "{\"name\": \"demo\"}\n",
    "generated/api.ts": "// @generated by protoc, DO NOT EDIT\nexport const x = 1;\n",
    "vendor/lib.js": "module.exports = 1;\n",
    "gen/domain.ts": "export function loadGenome() {}\n",
    "tests/fixtures/sample.json": "{}\n",
    "package-lock.json": "{}\n",
    ".github/CODEOWNERS": "* @owner\n",
    "CHANGELOG.md": "# Changelog\n",
    "LICENSE": "MIT\n",
}


def invoke(*args, cwd=None):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args], capture_output=True, text=True, cwd=cwd, check=False
    )


def run(*args, cwd=None, expect=0):
    result = invoke(*args, cwd=cwd)
    if result.returncode != expect:
        raise AssertionError(f"{' '.join(args)}\n{result.stdout}\n{result.stderr}")
    return result.stdout


class AuditFlow(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.repo = root / "repo"
        self.work = root / "work"
        for rel, text in FILES.items():
            path = self.repo / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        (self.repo / "logo.png").write_bytes(b"\x89PNG\x00\x00")
        git = lambda *a: subprocess.run(["git", "-C", str(self.repo), *a], check=True, capture_output=True)
        git("init", "-q")
        git("-c", "user.email=t@t", "-c", "user.name=t", "add", ".")
        git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init")
        (self.repo / "untracked.ts").write_text("export const y = 2;\n")

    def tearDown(self):
        self.tmp.cleanup()

    def inventory(self, *extra):
        run("inventory", "--repo", str(self.repo), "--work", str(self.work), "--rubric", str(RUBRIC), "--shard-lines", "20", *extra)
        return json.loads((self.work / "inventory.json").read_text())

    def test_inventory_classifies_and_shards_every_file(self):
        inventory = self.inventory()
        by_path = {f["path"]: f for f in inventory["files"]}
        expected = {
            "src/billing/invoice.ts": "source", "tests/billing/invoice.test.ts": "test", "migrations/001_init.sql": "schema",
            "scripts/release.sh": "script", "README.md": "docs", "package.json": "config", "generated/api.ts": "generated",
            "vendor/lib.js": "vendored", "gen/domain.ts": "generated", "tests/fixtures/sample.json": "data",
            "package-lock.json": "data", "logo.png": "binary", "untracked.ts": "source",
            ".github/CODEOWNERS": "config", "CHANGELOG.md": "docs", "LICENSE": "data",
        }
        for path, cls in expected.items():
            self.assertEqual(by_path[path]["class"], cls, path)
        self.assertEqual(len(inventory["properties"]), 19)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        assigned = sorted(p for s in shards for p in s["files"])
        self.assertEqual(assigned, sorted(f["path"] for f in inventory["files"] if f["treatment"] == "read"))
        self.assertGreater(len(shards), 1)

    def test_shard_planning_balances_an_oversized_file(self):
        files = [{"path": "huge.py", "lines": 1500}] + [
            {"path": f"small-{index}.py", "lines": 100} for index in range(10)
        ]
        shards = AUDIT.plan_shards(files, 500)
        self.assertEqual(len(shards), 5)
        small_loads = [shard["lines"] for shard in shards if "huge.py" not in shard["files"]]
        self.assertLessEqual(max(small_loads) - min(small_loads), 100)

    def test_intro_preserves_dynamic_values_and_layout(self):
        repository = "intro-repo-7"
        destination = "/tmp/intro-contract-audit.md"
        out = run("intro", "--repo", f"/very/long/path/{repository}", "--destination", destination)
        lines = out.splitlines()
        self.assertEqual(out.count(repository), 1)
        self.assertEqual(out.count(destination), 1)
        self.assertEqual(lines[-1].strip(), destination)
        self.assertLessEqual(max(map(len, lines)), 78)
        base = "origin/release-2026.08"
        ranged = run("intro", "--repo", f"/very/long/path/{repository}", "--base", base, "--chat-only")
        self.assertEqual(ranged.count(f"{base}..HEAD"), 1)
        self.assertEqual(ranged.count(repository), 1)
        self.assertLessEqual(max(map(len, ranged.splitlines())), 78)
        self.assertNotEqual(ranged, out)

    def test_scope_question_presents_two_bounded_choices(self):
        repository = "scope-repo-11"
        out = run("scope", "--repo", f"/work/{repository}")
        lines = out.splitlines()
        choices = [line for line in lines if line.startswith(("  1  ", "  2  "))]
        self.assertEqual(len(choices), 2)
        self.assertEqual(out.count(repository), 1)
        self.assertLessEqual(max(map(len, lines)), 78)

    def test_whole_repository_ignores_finding_scope(self):
        inventory = self.inventory("--shard-lines", "100000")
        self.assertIsNone(inventory["range"])
        self.assertEqual({file["treatment"] for file in inventory["files"]} & {"context"}, set())
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        finding = {
            "property": "Use distinctive domain names", "severity": "MED", "path": "src/billing/invoice.ts", "line": 1,
            "evidence": "export function process(input) {", "observation": "generic verb", "symbol": "process",
            "recipe": ["rename"], "scope": "follow-up", "traces_to": "src/billing/invoice.ts",
        }
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, shard["files"], [], [finding])))
        run("verify", "--work", str(self.work))
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(len(ledger["findings"]), 1)
        self.assertNotIn("scope", ledger["findings"][0])
        self.assertNotIn("traces_to", ledger["findings"][0])
        narrative = {"property_checks": {p: "checked" for p in inventory["properties"][1:]}, "properties_not_applicable": {}}
        score = AUDIT.audit_score(inventory, ledger, narrative)
        self.assertEqual((score["scope"], score["affected"]), ("repository", 1))

    def test_override_rescues_misclassified_directory(self):
        inventory = self.inventory("--override", "gen=source")
        by_path = {f["path"]: f for f in inventory["files"]}
        self.assertEqual(by_path["gen/domain.ts"]["treatment"], "read")

    def test_override_warns_when_prefix_matches_nothing(self):
        result = invoke("inventory", "--repo", str(self.repo), "--work", str(self.work), "--rubric", str(RUBRIC),
                        "--override", "missing=source")
        self.assertEqual(result.returncode, 0)
        self.assertIn("warning: --override prefix matches no inventory path: missing", result.stderr)

    def test_work_dir_inside_repo_is_refused(self):
        result = subprocess.run([sys.executable, str(SCRIPT), "inventory", "--repo", str(self.repo), "--work",
                                 str(self.repo / "work"), "--rubric", str(RUBRIC)], capture_output=True, text=True,
                                check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse((self.repo / "work").exists())

    def test_shard_prompt_names_missing_seed_step(self):
        self.inventory()
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        result = invoke("shard-prompt", "--work", str(self.work), "--shard", shard["id"])
        self.assertEqual(result.returncode, 1)
        self.assertIn("missing vocabulary.json (run seed vocabulary (step 2))", result.stderr)

    def artifact(self, shard, read, skipped, findings, declare=True):
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        return {"shard": shard["id"], "properties_checked": properties if declare else properties[:-1],
                "files_read": [{"path": p, "lines": 1} for p in read],
                "files_skipped": [{"path": p, "reason": "ran out of budget"} for p in skipped],
                "findings": findings, "cross_shard_leads": [], "vocabulary_additions": []}

    def test_shard_without_full_property_declaration_reads_nothing(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, shard["files"], [], [], declare=False)))
        out = run("verify", "--work", str(self.work), expect=1)
        self.assertIn("read 0/", out)
        self.assertIn("properties not declared checked", out)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], shard["files"])
        # Once the child covers every file the parent's message is recovered evidence, not a problem.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, child["files"], [], [])))
        out = run("verify", "--work", str(self.work))
        self.assertIn("uncovered 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(ledger["problems"], [])
        self.assertEqual(len(ledger["recovered"]), 1)

    def test_coverage_is_recomputed_from_present_artifacts(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        artifact = self.work / "shards" / f"{shard['id']}.json"
        artifact.write_text(json.dumps(self.artifact(shard, shard["files"], [], [])))
        self.assertIn("(100%)", run("verify", "--work", str(self.work)))
        artifact.unlink()
        out = run("verify", "--work", str(self.work), expect=1)
        self.assertIn("read 0/", out)
        self.assertEqual(json.loads((self.work / "shards.json").read_text())["shards"][0]["status"], "pending")
        artifact.write_text("{not json")
        out = run("verify", "--work", str(self.work), expect=1)
        self.assertIn("read 0/", out)
        self.assertIn("not valid JSON", out)

    def test_finding_ids_survive_later_findings_and_wrapped_evidence(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        first = {
            "property": "Use distinctive domain names", "severity": "MED", "path": "src/billing/invoice.ts", "line": 1,
            "evidence": "export function process(input) { return normalize(input);", "observation": "generic operation",
            "symbol": "process", "new_symbol": "processInvoice", "recipe": ["rename the operation"],
        }
        (self.work / "shards" / f"{shard['id']}.json").write_text(
            json.dumps(self.artifact(shard, shard["files"], [], [first]))
        )
        run("verify", "--work", str(self.work))
        original_id = json.loads((self.work / "ledger.json").read_text())["findings"][0]["id"]
        earlier_path = {
            "property": "Record repository-wide search conventions", "severity": "LOW", "path": "README.md", "line": 1,
            "evidence": "# Demo", "observation": "search guidance is absent", "recipe": ["add search guidance"],
            "accept": [{"argv": ["git", "grep", "-n", "search", "--", "README.md"], "expect": "one guide"}],
        }
        (self.work / "shards" / "main.json").write_text(json.dumps({
            "shard": "main", "findings": [earlier_path], "cross_shard_leads": [], "vocabulary_additions": []
        }))
        run("verify", "--work", str(self.work))
        findings = json.loads((self.work / "ledger.json").read_text())["findings"]
        self.assertEqual(next(finding["id"] for finding in findings if finding["path"].startswith("src/")), original_id)
        self.assertEqual(len({finding["id"] for finding in findings}), 2)

    def test_full_flow_reconciles_verifies_measures_and_renders(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        prompt = run("shard-prompt", "--work", str(self.work), "--shard", shard["id"])
        self.assertIn("## Rubric", prompt)
        self.assertIn("src/billing/invoice.ts", prompt)
        self.assertEqual(prompt.count(str(self.work / "shards" / f"{shard['id']}.json")), 1)
        good = {
            "property": "Use distinctive domain names", "severity": "HIGH", "path": "src/billing/invoice.ts", "line": 1,
            "evidence": "export function process(input) {", "observation": "generic verb without its object",
            "symbol": "process", "new_symbol": "processInvoice", "recipe": ["rename process -> processInvoice"],
        }
        fabricated = {**good, "path": "src/shared/utils.ts", "line": 1, "evidence": "this line does not exist"}
        no_fix = {**good, "path": "src/shared/utils.ts", "line": 2, "evidence": "export function process(a)", "recipe": None}
        both = {**good, "line": 2, "evidence": "return normalize(input);", "decision": {"question": "q", "options": ["a"]}}
        no_check = {**good, "line": 3, "evidence": "}", "symbol": None}
        read = [p for p in shard["files"] if p != "README.md"]
        artifact = self.artifact(shard, read, ["README.md"], [good, fabricated, no_fix, both, no_check])
        artifact["vocabulary_additions"] = [
            {"concept": "invoice", "spellings": ["invoice"], "paths": ["src/billing/invoice.ts:1"]}
        ]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(artifact))
        out = run("verify", "--work", str(self.work), expect=1)
        self.assertIn("RE-DISPATCH", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual([f["id"] for f in ledger["findings"]], ["F-001"])
        self.assertEqual(len(ledger["dropped"]), 4)
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        child = next(s for s in shards if s["parent"] == shard["id"])
        self.assertEqual(child["files"], ["README.md"])
        # Second miss on the re-dispatched shard turns the file into uncovered rather than looping.
        (self.work / "shards" / f"{child['id']}.json").write_text(json.dumps(self.artifact(child, [], ["README.md"], [])))
        (self.work / "shards" / "main.json").write_text(json.dumps({"shard": "main", "files_read": [], "files_skipped": [], "findings": [
            {"property": "Make paths and exports say where code lives", "severity": "MED", "path": "src/shared/utils.ts", "line": 1,
             "evidence": "export * from './x';", "observation": "star re-export hides names",
             "decision": {"question": "which module owns utils", "options": ["billing", "delete"],
                          "recommendation": "Delete the generic re-export so billing owns the symbol."},
             "accept": [{"argv": ["git", "grep", "-n", "export \\*", "--", "src"], "expect": "0 hits"}]},
            dict(good)]}))
        out = run("verify", "--work", str(self.work), expect=1)
        self.assertIn("uncovered 1", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(sorted(f["shard"] for f in ledger["findings"]), sorted(["main", shard["id"]]))
        # The main-pass copy of `good` is an exact duplicate and must not get a second ID.
        self.assertEqual(len(ledger["findings"]), 2)
        self.assertTrue(any("duplicate key (property, path, line, normalized evidence)" in d["reason"] for d in ledger["dropped"]))
        self.assertEqual(next(f for f in ledger["files"] if f["path"] == "README.md")["status"], "uncovered")
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [
            {"concept": "organization", "spellings": ["organization"], "documented": "README.md:2",
             "reach": {"owner": "migrations/001_init.sql", "wiring": None, "contract": "n/a", "tests": "n/a", "absence": "missing/file.ts"},
             "findings": []}], "rejected": []}))
        ids = [f["id"] for f in ledger["findings"]]
        packets = {"packets": [
            {"id": "P-02", "title": "Rename process", "findings": ids[:1], "after": ["P-01"], "accept": []},
            {"id": "P-01", "title": "Own utils", "findings": ids[1:], "after": [], "creates": ["AGENTS.md"],
             "accept": [{"argv": ["git", "grep", "-n", "export \\*"], "expect": "0 hits"}]}]}
        (self.work / "packets.json").write_text(json.dumps(packets))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        clean = [p for p in properties if p not in ("Use distinctive domain names", "Make paths and exports say where code lives")]
        narrative = {"verdict": "Names are generic.", "method": "1 shard | sequential.",
                     "property_checks": {p: "checked in every file read; no violation" for p in clean[1:]},
                     "themes": [
                         {"title": "Give invoice processing a domain name",
                          "explanation": "The main operation is named process, so searches reach unrelated operations. Rename it to processInvoice.",
                          "findings": [ids[0]], "packets": ["P-02"]},
                         {"title": "Import the billing contract directly",
                          "explanation": "A star export hides the owning module, so readers must open it to discover the contract. Remove the generic re-export.",
                          "findings": [ids[1]], "packets": ["P-01"]},
                     ]}
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        out = run("measure", "--work", str(self.work), expect=1)
        self.assertIn("2 packets", out)
        self.assertIn("packet P-02: accept must be a non-empty list", out)
        self.assertIn("path not in inventory: missing/file.ts", out)
        self.assertIn("unresolved addition invoice", out)
        self.assertIn("misses wiring without an accepted finding", out)
        self.assertIn(f"no property_checks evidence: {clean[0]!r}", out)
        # Fixing the artifacts and rerunning measure clears its problems instead of accumulating them.
        packets["packets"][0]["accept"] = [{"argv": ["git", "grep", "-nw", "--", "processInvoice"], "expect": "definition and calls"}]
        (self.work / "packets.json").write_text(json.dumps(packets))
        narrative["property_checks"][clean[0]] = "git grep -n ' as ' -- '*.ts' = 0"
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        vocabulary = json.loads((self.work / "vocabulary.json").read_text())
        vocabulary["concepts"][0]["reach"]["absence"] = "n/a"
        vocabulary["concepts"][0]["findings"] = [ids[0]]
        vocabulary["concepts"].append({
            "concept": "invoice", "spellings": ["invoice"], "documented": None,
            "reach": {"owner": "src/billing/invoice.ts", "wiring": "n/a", "contract": "n/a",
                      "tests": "tests/billing/invoice.test.ts", "absence": "n/a"},
            "findings": [],
        })
        (self.work / "vocabulary.json").write_text(json.dumps(vocabulary))
        out = run("measure", "--work", str(self.work))
        self.assertIn("problems 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        blast = next(f for f in ledger["findings"] if f["id"] == "F-001")["blast"]
        self.assertEqual(blast["files"], 3)
        self.assertEqual(blast["new_symbol_hits"], 0)
        self.assertEqual([p["id"] for p in ledger["packets"]], ["P-01", "P-02"])
        self.assertIn("AGENTS.md", ledger["packets"][0]["files"])
        self.assertEqual(ledger["trials"][0]["reach"]["absence"]["mark"], "-")
        self.assertEqual(ledger["trials"][1]["documented"]["mark"], " ")
        self.assertEqual(ledger["measure_problems"], [])
        report = self.work / "audit.md"
        out = run("render", "--work", str(self.work), "--out", str(report))
        text = report.read_text()
        lines = text.splitlines()
        self.assertEqual(len([line for line in lines if line.startswith("## ")]), 10)
        self.assertEqual(len([line for line in lines if line.startswith("### F-")]), len(ids))
        self.assertEqual(len([line for line in lines if line.startswith("### P-")]), 2)
        in_fence = False
        for line in lines:
            if line.startswith("```"):
                in_fence = not in_fence
            elif in_fence:
                self.assertLessEqual(len(line), 100, line)
        self.assertFalse(in_fence)
        audit = json.loads((self.work / "audit.json").read_text())
        self.assertEqual([f["id"] for f in audit["findings"]], ids)
        self.assertEqual(len(audit["dropped"]), 5)
        self.assertEqual(audit["problems"], [])
        self.assertIsNone(audit["score"]["value"])
        card = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        card_lines = card.rstrip().splitlines()
        separators = [line for line in card_lines if line and set(line) == {"─"}]
        self.assertEqual(len(separators), 4)
        self.assertTrue(all(len(line) == 78 for line in separators))
        self.assertLessEqual(max(map(len, card_lines)), 78)
        self.assertTrue(card_lines[-1].endswith(str(report.resolve())))

    def test_measure_rejects_open_or_untrialed_vocabulary(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        artifact = self.artifact(shard, shard["files"], [], [])
        artifact["vocabulary_additions"] = [
            {"concept": "invoice", "spellings": ["invoice", "bill"], "paths": ["src/billing/invoice.ts"]}
        ]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(artifact))
        run("verify", "--work", str(self.work))
        (self.work / "vocabulary.json").write_text(json.dumps({
            "concepts": [{
                "concept": "organization", "spellings": ["organization"], "documented": "README.md:2",
                "reach": {"owner": "src/shared/utils.ts:1"}, "findings": [],
            }],
            "rejected": [],
        }))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        narrative = {
            "verdict": "No findings.", "method": "1 shard, sequential.", "themes": [],
            "property_checks": {property_name: "checked" for property_name in properties},
        }
        (self.work / "narrative.json").write_text(json.dumps(narrative))
        (self.work / "packets.json").write_text(json.dumps({"packets": []}))
        out = run("measure", "--work", str(self.work), expect=1)
        self.assertIn("unresolved addition invoice", out)
        self.assertIn("not trialed: missing reach wiring, contract, tests, absence", out)
        self.assertIn("proof contains none of its spellings", out)
        inventory = json.loads((self.work / "inventory.json").read_text())
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertIsNone(AUDIT.audit_score(inventory, ledger, narrative)["value"])

        vocabulary = json.loads((self.work / "vocabulary.json").read_text())
        vocabulary["concepts"][0]["reach"] = {
            "owner": "migrations/001_init.sql", "wiring": "n/a", "contract": "n/a",
            "tests": "n/a", "absence": "n/a",
        }
        vocabulary["concepts"].append({
            "concept": "invoice", "spellings": ["invoice"], "documented": None,
            "reach": {"owner": "src/billing/invoice.ts", "wiring": "n/a", "contract": "n/a",
                      "tests": "tests/billing/invoice.test.ts", "absence": "n/a"},
            "findings": [],
        })
        (self.work / "vocabulary.json").write_text(json.dumps(vocabulary))
        out = run("measure", "--work", str(self.work))
        self.assertIn("problems 0", out)
        ledger = json.loads((self.work / "ledger.json").read_text())
        resolution = ledger["vocabulary_resolutions"][0]
        self.assertEqual((resolution["disposition"], resolution["target"]), ("merged", "invoice"))
        self.assertEqual(resolution["unadopted"], ["bill"])
        self.assertEqual(AUDIT.audit_score(inventory, ledger, narrative)["value"], 100)

    def test_measure_names_the_missing_stage_artifact(self):
        self.inventory("--shard-lines", "100000")
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(
            json.dumps(self.artifact(shard, shard["files"], [], []))
        )
        run("verify", "--work", str(self.work))
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        result = invoke("measure", "--work", str(self.work))
        self.assertEqual(result.returncode, 1)
        self.assertIn("missing packets.json (run packets and narrative (step 5))", result.stderr)
        (self.work / "packets.json").write_text(json.dumps({"packets": [{}]}))
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        (self.work / "narrative.json").write_text(json.dumps({
            "verdict": "No findings.", "method": "sequential", "themes": [],
            "property_checks": {property_name: "checked" for property_name in properties},
        }))
        out = run("measure", "--work", str(self.work), expect=1)
        self.assertIn("packet entry 1: needs a non-empty id", out)
        (self.work / "vocabulary.json").write_text("{")
        result = invoke("trial", "--work", str(self.work))
        self.assertEqual(result.returncode, 1)
        self.assertIn("invalid JSON in vocabulary.json at line 1, column 2", result.stderr)

    def test_vocabulary_search_finds_compound_identifiers(self):
        path = self.repo / "src" / "organization-runtime.ts"
        path.write_text("export const organizationId = 'o1';\nexport class OrganizationRepository {}\n")
        inventory = self.inventory()
        by_path = {file["path"]: file for file in inventory["files"]}
        hits = AUDIT.grep_hits(self.repo, "organization", by_path, whole_word=False)
        self.assertIn("src/organization-runtime.ts:1", hits)
        self.assertIn("src/organization-runtime.ts:2", hits)

    def test_trial_drafts_all_surfaces_and_short_proofs_need_whole_words(self):
        self.inventory()
        (self.work / "vocabulary.json").write_text(json.dumps({
            "concepts": [{"concept": "organization", "spellings": ["organization"], "findings": []}],
            "rejected": [],
        }))
        out = run("trial", "--work", str(self.work))
        self.assertIn("filled 6 draft proofs", out)
        concept = json.loads((self.work / "vocabulary.json").read_text())["concepts"][0]
        self.assertEqual(set(concept["reach"]), {"owner", "wiring", "contract", "tests", "absence"})
        self.assertEqual(concept["documented"], "README.md:2")
        (self.repo / "README.md").write_text("This audit is deliberately slow.\n")
        inventory = json.loads((self.work / "inventory.json").read_text())
        by_path = {file["path"]: file for file in inventory["files"]}
        self.assertEqual(
            AUDIT.proof_error(self.repo, "README.md:1", ["LOW"], by_path),
            "proof contains none of its spellings: README.md:1",
        )

    def test_score_uses_worst_severity_per_property(self):
        properties = AUDIT.rubric_headings(RUBRIC)
        affected = {properties[0], properties[4], properties[11]}
        inventory = {"properties": properties}
        findings = [
            {"property": properties[0], "severity": "MED"},
            {"property": properties[0], "severity": "LOW"},
            {"property": properties[4], "severity": "MED"},
            {"property": properties[11], "severity": "MED"},
        ]
        ledger = {"findings": findings, "files": [], "problems": [], "measure_problems": [],
                  "unassigned_findings": []}
        narrative = {"property_checks": {prop: "checked" for prop in properties if prop not in affected},
                     "properties_not_applicable": {}}
        score = AUDIT.audit_score(inventory, ledger, narrative)
        self.assertEqual(score["value"], 92)
        self.assertEqual(score["clean"], 16)
        self.assertEqual(score["affected"], 3)
        self.assertEqual([dimension["value"] for dimension in score["dimensions"]], [88, 83, 100, 100, 100])
        mapped = {prop for _, dimension_properties in AUDIT.DIMENSIONS for prop in dimension_properties}
        self.assertEqual(set(properties), mapped)
        narrative["property_checks"].pop(properties[1])
        self.assertIsNone(AUDIT.audit_score(inventory, ledger, narrative)["value"])

    def test_card_preserves_visual_counts_and_absolute_report_path(self):
        properties = AUDIT.rubric_headings(RUBRIC)
        affected = {properties[0], properties[4], properties[11]}
        findings = [
            {"id": "F-001", "property": properties[0], "severity": "MED", "path": "src/config.rs", "line": 10},
            {"id": "F-002", "property": properties[4], "severity": "MED", "path": "src/overlay.rs", "line": 20},
            {"id": "F-003", "property": properties[11], "severity": "MED", "path": "src/tui.rs", "line": 30},
            {"id": "F-004", "property": properties[0], "severity": "LOW", "path": "src/tui.rs", "line": 40},
        ]
        files = [{"path": f"src/file-{index}.rs", "treatment": "read", "status": "read-in-full"} for index in range(34)]
        ledger = {"findings": findings, "files": files, "problems": [], "measure_problems": [],
                  "unassigned_findings": []}
        theme_title = "Give owners domain-specific names"
        narrative = {
            "verdict": "Search reaches every owner, but three properties add avoidable reconstruction.",
            "property_checks": {prop: "checked" for prop in properties if prop not in affected},
            "properties_not_applicable": {},
            "themes": [{"title": theme_title,
                        "explanation": "Several owner names need module context, so a reader opens extra files before finding the right owner. Split the TUI by responsibility.",
                        "findings": [f["id"] for f in findings], "packets": ["P-01"]}],
        }
        score = AUDIT.audit_score({"properties": properties}, ledger, narrative)
        audit = {
            "repository": {"repo": "/repos/mdmanager", "head": "de72aec815b61234", "branch": "main", "dirty": []},
            "narrative": narrative, "score": score, "findings": findings,
            "packets": [{"id": "P-01", "title": theme_title, "findings": [f["id"] for f in findings]}],
            "trials": [], "files": files, "dropped": [], "problems": [],
        }
        (self.work / "audit.json").parent.mkdir(parents=True, exist_ok=True)
        (self.work / "audit.json").write_text(json.dumps(audit))
        report = self.work / "audit.md"
        card = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        lines = card.rstrip().splitlines()
        property_rows = [line for line in lines if line.count("●") + line.count("○") == score["applicable"]]
        self.assertEqual(len(property_rows), 1)
        self.assertEqual(property_rows[0].count("●"), score["clean"])
        self.assertEqual(property_rows[0].count("○"), score["affected"])
        dimension_rows = [line for line in lines if line.count("●") + line.count("○") == 10]
        self.assertEqual(len(dimension_rows), len(score["dimensions"]))
        for row, dimension in zip(dimension_rows, score["dimensions"], strict=True):
            expected_filled = int(10 * dimension["value"] / 100 + 0.5)
            self.assertEqual(row.count("●"), expected_filled)
            self.assertEqual(row.count("○"), 10 - expected_filled)
        self.assertEqual(card.count(theme_title), 1)
        self.assertLessEqual(max(map(len, lines)), 78)
        self.assertTrue(lines[-1].endswith(str(report.resolve())))


class ChangeRangeFlow(unittest.TestCase):
    """A feature branch whose base moved on: the audited delta is merge-base..HEAD, never base..HEAD."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.repo = root / "repo"
        self.work = root / "work"
        for rel, text in FILES.items():
            path = self.repo / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        self.git("init", "-q", "-b", "main")
        self.git("add", ".")
        self.git("commit", "-qm", "init")
        self.git("checkout", "-qb", "feature")
        (self.repo / "src/billing/invoice.ts").write_text(
            "export function processInvoice(input) {\n  return normalize(input);\n}\nexport function process(x) { return x; }\n"
        )
        self.git("mv", "src/shared/utils.ts", "src/shared/helpers.ts")
        self.git("rm", "-q", "scripts/release.sh")
        (self.repo / "generated/client.ts").write_text("// @generated by protoc, DO NOT EDIT\nexport const client = 1;\n")
        (self.repo / "assets.png").write_bytes(b"\x89PNG\x00\x00")
        (self.repo / "rates.csv").write_text("a,b\n")
        self.git("add", "-A")
        self.git("commit", "-qm", "feature")
        self.git("checkout", "-q", "main")
        (self.repo / "README.md").write_text(FILES["README.md"] + "Main moved on.\n")
        self.git("commit", "-qam", "main moves")
        self.git("checkout", "-q", "feature")
        self.base = self.git("rev-parse", "main")
        self.merge_base = self.git("merge-base", "main", "HEAD")
        self.head = self.git("rev-parse", "HEAD")
        self.assertNotEqual(self.base, self.merge_base)

    def tearDown(self):
        self.tmp.cleanup()

    def git(self, *args):
        return subprocess.run(
            ["git", "-C", str(self.repo), "-c", "user.email=t@t", "-c", "user.name=t", *args],
            check=True, capture_output=True, text=True,
        ).stdout.strip()

    def inventory(self, *extra, base="main", expect=0):
        result = invoke("inventory", "--repo", str(self.repo), "--work", str(self.work), "--rubric", str(RUBRIC),
                        "--shard-lines", "100000", "--base", base, *extra)
        self.assertEqual(result.returncode, expect, result.stdout + result.stderr)
        return json.loads((self.work / "inventory.json").read_text()) if expect == 0 else result

    def artifact(self, shard, findings, leads=()):
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        return {"shard": shard["id"], "properties_checked": properties,
                "files_read": [{"path": p, "lines": 1} for p in shard["files"]], "files_skipped": [],
                "findings": findings, "cross_shard_leads": list(leads), "vocabulary_additions": []}

    def finding(self, property_index, path, line, evidence, **extra):
        properties = json.loads((self.work / "inventory.json").read_text())["properties"]
        return {"property": properties[property_index], "severity": "MED", "path": path, "line": line,
                "evidence": evidence, "observation": "generic name", "recipe": ["rename it"],
                "accept": [{"argv": ["git", "grep", "-nw", "--", "process"], "expect": "0 hits"}], **extra}

    def test_unresolved_base_no_merge_base_and_empty_range_write_nothing(self):
        for base, token in (("no-such-ref", "no-such-ref"), ("HEAD", self.head[:12])):
            result = self.inventory(base=base, expect=1)
            self.assertIn(token, result.stderr)
            self.assertFalse((self.work / "inventory.json").exists())
        self.git("checkout", "-q", "--orphan", "solo")
        self.git("commit", "-qm", "orphan", "--allow-empty")
        self.git("checkout", "-q", "feature")
        result = self.inventory(base="solo", expect=1)
        self.assertIn(self.head[:12], result.stderr)
        self.assertFalse((self.work / "inventory.json").exists())

    def test_base_refuses_scope_and_writes_nothing(self):
        result = self.inventory("--scope", "src/billing", expect=1)
        self.assertNotEqual(result.stderr.strip(), "")
        self.assertFalse((self.work / "inventory.json").exists())
        self.assertFalse((self.work / "shards.json").exists())

    def test_copy_of_an_unchanged_source_keeps_its_origin(self):
        source, copy = "migrations/001_init.sql", "migrations/002_init_copy.sql"
        (self.repo / copy).write_text((self.repo / source).read_text())
        self.git("add", copy)
        self.git("commit", "-qm", "copy an unchanged schema file")
        inventory = self.inventory()
        changes = {change["path"]: change for change in inventory["range"]["changed"]}
        self.assertEqual((changes[copy]["status"], changes[copy]["old_path"]), ("C", source))
        self.assertNotIn(source, changes)
        by_path = {file["path"]: file for file in inventory["files"]}
        self.assertEqual((by_path[copy]["treatment"], by_path[copy]["old_path"]), ("read", source))
        self.assertEqual(by_path[source]["treatment"], "context")
        self.assertEqual(changes["src/shared/helpers.ts"]["old_path"], "src/shared/utils.ts")
        self.assertEqual(changes["scripts/release.sh"]["status"], "D")

    def test_unsupported_changed_paths_stop_the_inventory(self):
        self.git("update-index", "--add", "--cacheinfo", "160000,4b825dc642cb6eb9a060e54bf8d69288fbee4904,libs/dep")
        (self.repo / "libs/dep").mkdir(parents=True)
        (self.repo / "dangling").symlink_to("missing-target")
        # A valid symlink resolves to a regular file, so is_file() alone would read the target in its place.
        (self.repo / "alias.ts").symlink_to("src/billing/invoice.ts")
        self.git("add", "dangling", "alias.ts")
        self.git("commit", "-qm", "gitlink, dangling symlink, valid symlink")
        self.assertEqual(self.git("status", "--porcelain"), "")
        result = self.inventory(expect=1)
        for path in ("libs/dep", "dangling", "alias.ts"):
            self.assertIn(path, result.stderr)
        self.assertNotIn("src/billing/invoice.ts", result.stderr)
        self.assertFalse((self.work / "inventory.json").exists())
        self.git("rm", "-q", "--cached", "libs/dep")
        self.git("rm", "-q", "dangling", "alias.ts")
        self.git("commit", "-qm", "drop them")
        inventory = self.inventory()
        self.assertEqual({c["path"] for c in inventory["range"]["changed"] if c["status"] == "D"}, {"scripts/release.sh"})

    def test_worktree_must_match_head_before_and_during_the_audit(self):
        (self.repo / "src/billing/invoice.ts").write_text("export function edited() {}\n")
        result = self.inventory(expect=1)
        self.assertIn(self.head[:12], result.stderr)
        self.assertFalse((self.work / "inventory.json").exists())
        self.git("checkout", "--", "src/billing/invoice.ts")
        (self.repo / "scratch.ts").write_text("export const scratch = 1;\n")
        inventory = self.inventory()
        self.assertNotIn("scratch.ts", {file["path"] for file in inventory["files"]})
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, [])))
        run("verify", "--work", str(self.work))
        self.assertEqual(json.loads((self.work / "ledger.json").read_text())["problems"], [])
        self.git("commit", "-qm", "moved", "--allow-empty")
        run("verify", "--work", str(self.work), expect=1)
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(len(ledger["problems"]), 1)
        self.assertIn(self.head[:12], ledger["problems"][0])
        self.assertIsNone(AUDIT.audit_score(inventory, ledger, {"property_checks": {}})["value"])

    def test_range_records_shas_renames_deletes_and_listed_changes(self):
        inventory = self.inventory()
        audited = inventory["range"]
        self.assertEqual(
            (audited["base_input"], audited["base"], audited["merge_base"], audited["head"]),
            ("main", self.base, self.merge_base, self.head),
        )
        by_status = {change["path"]: change for change in audited["changed"]}
        self.assertEqual(by_status["src/shared/helpers.ts"]["old_path"], "src/shared/utils.ts")
        self.assertEqual(by_status["src/shared/helpers.ts"]["status"], "R")
        self.assertEqual(by_status["scripts/release.sh"]["status"], "D")
        self.assertEqual(by_status["src/billing/invoice.ts"]["status"], "M")
        by_path = {file["path"]: file for file in inventory["files"]}
        self.assertNotIn("scripts/release.sh", by_path)
        self.assertNotIn("README.md", by_status)
        self.assertEqual(by_path["src/shared/helpers.ts"]["old_path"], "src/shared/utils.ts")
        self.assertEqual(by_path["generated/client.ts"]["treatment"], "boundary")
        self.assertEqual(by_path["assets.png"]["treatment"], "listed")
        self.assertEqual(by_path["rates.csv"]["treatment"], "listed")
        self.assertEqual({file["treatment"] for file in inventory["files"] if file["path"] in by_status} & {"context"}, set())
        self.assertEqual(by_path["README.md"]["treatment"], "context")
        self.assertEqual(by_path["tests/billing/invoice.test.ts"]["treatment"], "context")
        shards = json.loads((self.work / "shards.json").read_text())["shards"]
        self.assertEqual(sorted(p for s in shards for p in s["files"]), ["src/billing/invoice.ts", "src/shared/helpers.ts"])
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        prompt = run("shard-prompt", "--work", str(self.work), "--shard", shards[0]["id"])
        self.assertEqual(prompt.count("src/shared/utils.ts"), 2)
        self.assertEqual(prompt.count("scripts/release.sh"), 1)
        self.assertEqual(prompt.count(f"{self.merge_base[:12]}..{self.head[:12]}"), 1)

    def test_context_is_searchable_but_never_coverage(self):
        inventory = self.inventory()
        by_path = {file["path"]: file for file in inventory["files"]}
        self.assertIn("README.md:2", AUDIT.grep_hits(self.repo, "organization", by_path, whole_word=False))
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        finding = self.finding(0, "src/billing/invoice.ts", 4, "export function process(x)", symbol="process",
                               scope="change", traces_to="src/billing/invoice.ts")
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, [finding])))
        out = run("verify", "--work", str(self.work))
        ledger = json.loads((self.work / "ledger.json").read_text())
        readable = [file for file in ledger["files"] if file["treatment"] == "read"]
        context = [file for file in ledger["files"] if file["treatment"] == "context"]
        self.assertEqual(len(readable), 2)
        self.assertEqual(len(context), len(inventory["files"]) - 5)
        self.assertEqual({file["status"] for file in readable}, {"read-in-full"})
        self.assertEqual({file["status"] for file in context}, {"context"})
        self.assertIn(f"{len(readable)}/{len(readable)}", out)
        self.assertIn(str(len(context)), out)
        self.assertEqual(len(ledger["shards"]), 1)
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [
            {"concept": "organization", "spellings": ["organization"], "documented": "README.md:2",
             "reach": {"owner": "migrations/001_init.sql", "wiring": "n/a", "contract": "n/a", "tests": "n/a", "absence": "n/a"},
             "findings": []}], "rejected": []}))
        (self.work / "shards" / "main.json").write_text(json.dumps({
            "shard": "main", "findings": [], "vocabulary_additions": [],
            "cross_shard_leads": [{"lead": "client.ts is emitted from the invoice module",
                                   "paths": ["generated/client.ts", "src/billing/invoice.ts"]}],
        }))
        run("verify", "--work", str(self.work))
        (self.work / "packets.json").write_text(json.dumps({"packets": [
            {"id": "P-01", "title": "Rename process", "findings": ["F-001"], "after": [],
             "accept": [{"argv": ["git", "grep", "-nw", "--", "process"], "expect": "0 hits"}]}]}))
        properties = inventory["properties"]
        (self.work / "narrative.json").write_text(json.dumps({
            "verdict": "Generic verb.", "method": "1 shard.", "property_checks": {p: "checked" for p in properties[1:]},
            "themes": [{"title": "Rename process", "explanation": "Generic. Rename.", "findings": ["F-001"], "packets": ["P-01"]}],
        }))
        run("measure", "--work", str(self.work))
        ledger = json.loads((self.work / "ledger.json").read_text())
        blast = ledger["findings"][0]["blast"]
        # The symbol lives in two changed files and one unchanged test: context counts toward blast radius.
        self.assertIn("tests/billing/invoice.test.ts:1", blast["paths"])
        self.assertEqual(blast["files"], 3)
        self.assertEqual(ledger["trials"][0]["reach"]["owner"]["mark"], "x")
        self.assertEqual(ledger["trials"][0]["documented"]["mark"], "x")

    def test_changed_boundary_file_needs_a_generator_lead(self):
        inventory = self.inventory()
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(shard, [])))
        run("verify", "--work", str(self.work))
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        (self.work / "packets.json").write_text(json.dumps({"packets": []}))
        (self.work / "narrative.json").write_text(json.dumps({
            "verdict": "Clean.", "method": "1 shard.", "themes": [],
            "property_checks": {p: "checked" for p in inventory["properties"]},
        }))
        out = run("measure", "--work", str(self.work), expect=1)
        self.assertIn("generated/client.ts", out)
        self.assertEqual(json.loads((self.work / "ledger.json").read_text())["measure_problems"][0].count("generated/client.ts"), 1)
        # Naming only the boundary file, a path outside the inventory, or a non-maintained path verifies nothing.
        for paths in (
            ["generated/client.ts"],
            ["generated/client.ts", "api.proto"],
            ["generated/client.ts", "generated/api.ts", "vendor/lib.js", "rates.csv"],
        ):
            (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(
                shard, [], leads=[{"lead": "generated from api.proto", "paths": paths}]
            )))
            run("verify", "--work", str(self.work))
            run("measure", "--work", str(self.work), expect=1)
            self.assertEqual(len(json.loads((self.work / "ledger.json").read_text())["measure_problems"]), 1, paths)
        # An unchanged maintained context path is a valid verification target and stays context, not coverage.
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(
            shard, [], leads=[{"lead": "generated from the documented contract", "paths": ["generated/client.ts", "README.md"]}]
        )))
        run("verify", "--work", str(self.work))
        run("measure", "--work", str(self.work))
        ledger = json.loads((self.work / "ledger.json").read_text())
        self.assertEqual(ledger["measure_problems"], [])
        by_path = {file["path"]: file for file in ledger["files"]}
        self.assertEqual((by_path["README.md"]["treatment"], by_path["README.md"]["status"]), ("context", "context"))
        self.assertEqual(sum(file["status"] == "read-in-full" for file in ledger["files"]), len(shard["files"]))

    def scoped_flow(self):
        """Verify a mixed shard: two change findings, two follow-ups, and four that omit or misstate causality."""
        inventory = self.inventory()
        shard = json.loads((self.work / "shards.json").read_text())["shards"][0]
        findings = [
            self.finding(0, "src/billing/invoice.ts", 4, "export function process(x)",
                         scope="change", traces_to="src/billing/invoice.ts"),
            self.finding(1, "tests/billing/invoice.test.ts", 1, "import { process }",
                         scope="change", traces_to="src/billing/invoice.ts"),
            self.finding(2, "README.md", 2, "organization concept", scope="follow-up", traces_to="scripts/release.sh"),
            self.finding(3, "README.md", 1, "# Demo"),
            self.finding(4, "package.json", 1, "demo", scope="follow-up", traces_to="src/nowhere.ts"),
            # A changed file gets no defaults: an untouched line needs both fields stated.
            self.finding(5, "src/billing/invoice.ts", 2, "return normalize(input);", scope="follow-up"),
            self.finding(6, "src/billing/invoice.ts", 2, "return normalize(input);",
                         scope="follow-up", traces_to="src/billing/invoice.ts"),
            self.finding(7, "src/billing/invoice.ts", 4, "export function process(x)", traces_to="src/billing/invoice.ts"),
        ]
        (self.work / "shards" / f"{shard['id']}.json").write_text(json.dumps(self.artifact(
            shard, findings, leads=[{"lead": "emitted from the invoice module",
                                     "paths": ["generated/client.ts", "src/billing/invoice.ts"]}]
        )))
        run("verify", "--work", str(self.work), expect=1)
        return inventory, json.loads((self.work / "ledger.json").read_text())

    def test_outside_diff_findings_count_and_follow_ups_do_not_lower_the_score(self):
        inventory, ledger = self.scoped_flow()
        self.assertEqual(len(ledger["dropped"]), 4)
        self.assertEqual(
            Counter(finding["path"] for finding in ledger["dropped"]),
            {"README.md": 1, "package.json": 1, "src/billing/invoice.ts": 2},
        )
        self.assertTrue(all("scope" in f and "traces_to" in f for f in ledger["findings"]))
        by_path = {(f["path"], f["line"]): f for f in ledger["findings"]}
        self.assertEqual(by_path[("src/billing/invoice.ts", 4)]["scope"], "change")
        self.assertEqual(by_path[("src/billing/invoice.ts", 4)]["traces_to"], "src/billing/invoice.ts")
        self.assertEqual(by_path[("tests/billing/invoice.test.ts", 1)]["scope"], "change")
        self.assertEqual(by_path[("README.md", 2)]["traces_to"], "scripts/release.sh")
        self.assertEqual(by_path[("src/billing/invoice.ts", 2)]["traces_to"], "src/billing/invoice.ts")
        self.assertEqual(sum(f["scope"] == "follow-up" for f in ledger["findings"]), 2)
        properties = inventory["properties"]
        narrative = {"property_checks": {p: "checked" for p in properties[2:]},
                     "properties_not_applicable": {properties[10]: "no identity types in this change"}}
        score = AUDIT.audit_score(inventory, ledger, narrative)
        self.assertEqual(score["scope"], "change")
        self.assertEqual((score["applicable"], score["affected"], score["clean"]), (18, 2, 16))
        self.assertEqual(score["value"], 94)
        without = {**ledger, "findings": [f for f in ledger["findings"] if f["scope"] == "change"]}
        self.assertEqual(AUDIT.audit_score(inventory, without, narrative)["value"], score["value"])
        change_ids = [f["id"] for f in ledger["findings"] if f["scope"] == "change"]
        follow_ids = [f["id"] for f in ledger["findings"] if f["scope"] == "follow-up"]
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        packets = {"packets": [{"id": "P-01", "title": "Rename process", "findings": change_ids + follow_ids[:1],
                                "after": [], "accept": [{"argv": ["git", "grep", "-nw", "--", "process"], "expect": "0 hits"}]}]}
        (self.work / "packets.json").write_text(json.dumps(packets))
        (self.work / "narrative.json").write_text(json.dumps({
            "verdict": "Generic verb.", "method": "1 shard.", **narrative,
            "themes": [{"title": "Rename process", "explanation": "Generic. Rename.", "findings": change_ids, "packets": ["P-01"]}],
        }))
        out = run("measure", "--work", str(self.work), expect=1)
        self.assertIn(follow_ids[0], out)
        self.assertEqual(len(json.loads((self.work / "ledger.json").read_text())["measure_problems"]), 1)
        packets["packets"][0]["findings"] = change_ids
        (self.work / "packets.json").write_text(json.dumps(packets))
        self.assertIn("0 findings unassigned", run("measure", "--work", str(self.work)))
        self.assertEqual(json.loads((self.work / "ledger.json").read_text())["unassigned_findings"], [])

    def test_report_and_card_state_the_change_scope(self):
        inventory, ledger = self.scoped_flow()
        change_ids = [f["id"] for f in ledger["findings"] if f["scope"] == "change"]
        follow_ids = [f["id"] for f in ledger["findings"] if f["scope"] == "follow-up"]
        properties = inventory["properties"]
        (self.work / "vocabulary.json").write_text(json.dumps({"concepts": [], "rejected": []}))
        (self.work / "packets.json").write_text(json.dumps({"packets": [
            {"id": "P-01", "title": "Rename process", "findings": change_ids, "after": [],
             "accept": [{"argv": ["git", "grep", "-nw", "--", "process"], "expect": "0 hits"}]}]}))
        (self.work / "narrative.json").write_text(json.dumps({
            "verdict": "Generic verb.", "method": "1 shard.", "property_checks": {p: "checked" for p in properties[2:]},
            "properties_not_applicable": {properties[10]: "no identity types in this change"},
            "themes": [{"title": "Rename process", "explanation": "Generic. Rename.", "findings": change_ids, "packets": ["P-01"]}],
        }))
        run("measure", "--work", str(self.work))
        report = self.work / "audit.md"
        run("render", "--work", str(self.work), "--out", str(report))
        text = report.read_text()
        lines = text.splitlines()
        # Every full SHA appears in the header table and again in the coverage range block.
        for sha in (self.base, self.merge_base, self.head):
            self.assertEqual(text.count(sha), 2, sha)
        header = "\n".join(line for line in lines[:30] if line.startswith("| "))
        self.assertIn(f"`{self.merge_base}..{self.head}`", header)
        self.assertIn(f"`{self.base}`", header)
        self.assertEqual(text.count("`main`"), 1)
        readable = sum(file["treatment"] == "read" for file in ledger["files"])
        context = sum(file["treatment"] == "context" for file in ledger["files"])
        listed = sum(file["treatment"] in ("boundary", "listed") for file in ledger["files"])
        deleted = sum(change["status"] == "D" for change in inventory["range"]["changed"])
        # The field table carries every coverage count as a number, whatever its labels say.
        counts = Counter(int(n) for n in re.findall(r"(?<![\w`])\d+(?![\w`])", re.sub(r"`[^`]*`", "", header)))
        for value in (readable, context, listed, deleted):
            self.assertGreaterEqual(counts[value], 1, (value, counts))
        cards = [line.split(" - ")[0][4:] for line in lines if line.startswith("### F-")]
        self.assertEqual(cards, change_ids + follow_ids)
        self.assertEqual(len([line for line in lines if line.startswith("## ")]), 10)
        # Each finding card states the scope and trace the ledger holds for it, exactly once.
        by_id = {f["id"]: f for f in ledger["findings"]}
        for block in [block for block in text.split("\n### ")[1:] if block.startswith("F-")]:
            finding = by_id[block.split(" - ")[0]]
            self.assertEqual(
                sum(finding["scope"] in line and finding["traces_to"] in line for line in block.splitlines()), 1, finding["id"]
            )
        self.assertEqual(sum("scripts/release.sh" in line for line in lines if line.startswith("    ")), 1)
        self.assertNotIn("README.md", [line.split()[-1] for line in lines if line.startswith(("    read-in-full", "    context"))])
        audit = json.loads((self.work / "audit.json").read_text())
        self.assertEqual(audit["score"]["scope"], "change")
        self.assertEqual(audit["score"]["value"], 94)
        self.assertEqual(audit["range"]["merge_base"], self.merge_base)
        card = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        card_lines = card.rstrip().splitlines()
        self.assertLessEqual(max(map(len, card_lines)), 78)
        self.assertEqual(len([line for line in card_lines if line and set(line) == {"─"}]), 4)
        self.assertEqual(card.count(f"{self.merge_base[:12]}..{self.head[:12]}"), 1)
        self.assertEqual(card.count(self.base[:12]), 1)
        score_lines = [index for index, line in enumerate(card_lines) if line.strip().endswith(" 94")]
        self.assertEqual(len(score_lines), 1)
        # Two lines below the score, the status line counts scored findings and follow-ups as separate numbers.
        status_numbers = sorted(map(int, re.findall(r"\d+", card_lines[score_lines[0] + 2])))
        self.assertEqual(status_numbers, sorted([len(change_ids), len(follow_ids)]))
        coverage = [line for line in card_lines if f"{readable}/{readable}" in line]
        self.assertEqual(len(coverage), 1)
        for value in (deleted, context):
            self.assertIn(str(value), re.findall(r"\d+", coverage[0]))
        self.assertTrue(card_lines[-1].endswith(str(report.resolve())))
        whole = run("card", "--work", str(self.work), "--report", str(report.resolve()))
        self.assertEqual(whole, card)


if __name__ == "__main__":
    unittest.main()
